### ISSUE TITLE
How would one mock an error with partial response?

### ISSUE THREAD

**Issue by Twipped** [nearform/graphql-hooks#1088]
Say we have the following query:

```graphql
query someExample {
  itemA,
  itemB
}
```

I want to write a test case for if `itemB` produces an error, but `itemA` still returns. I'm trying to produce the following response:
```json
{
	"data": {
       "itemA": "foo",
       "itemB": null
    },
	"errors": [
		{
			"message": "Server Error",
			"locations": [
				{
					"line": 5,
					"column": 2
				}
			],
			"path": [
				"itemB"
			]
		}
	]
}
```

Simply returning the `LocalGraphQLError` as it says in the docs causes `data` to be null entirely. Is there a way to attach a data object to the error for return?

**Comment by Twipped** [comment]
From looking at the code, it seems there's no provision for this. https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/src/LocalGraphQLClient.ts#L62-L65

**Comment by matt-clarson** [comment]
@Twipped would it be useful to have the `LocalGraphQLClient` collect any errors in that a mock resolver function provides into the `graphQLErrors` object - like this:

```javascript
const client = new LocalGraphQLClient({
    someQuery: () => ({
        itemA: "foo",
        // because itemB is an instance of Error, collect it and replace it with null in the result
        itemB: new Error("Server Error")
    })
})

const {data, error} = await client.request(SOME_QUERY);
```

would give `data` as:

```javascript
{
    itemA: "foo",
    // replaced with null here as it's an error
    itemB: null
}
```

and `error` would be:

```javascript
{
    graphQLErrors: [
        // this is then the Error we used in the resolver
        { message: "Server Error" }
    ]
}
```

**Comment by Twipped** [comment]
@matt-clarson yeah, that would do the job. Another thought I had would be a `data` attribute on the `LocalGraphQLError` object, that'd probably be easier to implement.

**Comment by Twipped** [comment]
Awesome, thanks!
