### ISSUE TITLE
Type 'GraphQLClient' is not assignable to type 'Client'

### ISSUE THREAD

**Issue by jcan1995** [nearform/graphql-hooks#1142]
### Package

`graphql-hooks`
`graphql-hooks-ssr`
### Environment

- `graphql-hooks` version: 6.3.2  
- `graphql-hooks-ssr` version: 3.0.1
- `react` version: Using preact v10.11.0
- Browser: Chrome

### Description

Argument `client.cache` for `getInitialState` is required however `GraphQLClient` marks cache as optional. 

### How to reproduce

```jsx
export default async () => {
const client = new GraphQLClient({
        url: "<url>",
        cache: memCache(),
        ssrMode: true,
        fetchOptions: {
            credentials: 'include'
        }
    })
const App = <ServerApp request={props.request} client={client} />
const initialState = await getInitialState({ App, client, render: renderToString })
... 
}
```
<img width="745" alt="Screenshot 2023-12-13 at 4 02 27 PM" src="https://github.com/nearform/graphql-hooks/assets/10763136/7acd3545-d1d1-4d3b-9671-0f22a39dd683">

### Suggested solution (optional)

Mark GraphQLClient.cache as required ?

**Comment by jcan1995** [comment]
Implementing the following as a workaround
```
import type { Cache, GraphQLClient } from 'graphql-hooks'

type GraphQLClientWithCache = GraphQLClient & { cache: Cache }
const client = new GraphQLClient({
        url: "<url>",
        cache: memCache(),
        ssrMode: true,
        fetchOptions: {
            credentials: 'include'
        }
    }) as GraphQLClientWithCache
```

**Comment by ovhemert** [comment]
The `cache` argument is correctly defined as optional on the `GraphQLClient`. But only when using SSR, the cache is required as you can see in [these docs](https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks-ssr/README.md).

When passing on the `client` to the `getInitialState` of the `graphql-hooks-ssr`, it is therefore required. The types that define this are [here](https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks-ssr/index.d.ts).

It would not be a good option to require cache for everyone by changing in the type. The type definition of the client is actually different when passing on, so adjusting the object to pass along is the correct way here.

**Comment by jcan1995** [comment]
@ovhemert  Appreciate the quick response. 

What do we think about providing a new type from graphql-hooks-ssr or update the ssr quick start guide [here](https://github.com/nearform/graphql-hooks/tree/master/packages/graphql-hooks-ssr#quick-start)? Typescript will fail for users who just follow the guide.
