### ISSUE TITLE
Make `cache` option required for SSR

### ISSUE THREAD

**Issue by aribouius** [nearform/graphql-hooks#116]
### Package

`graphql-hooks-ssr`

### Environment

- `graphql-hooks-ssr` version: 1.0.5

### Description
When following the example found [here](https://github.com/nearform/graphql-hooks/tree/master/packages/graphql-hooks-ssr), it is not immediately obvious that using a caching plugin is required.  Some users might choose to begin with the simplest approach possible, and omit a cache provider. 

### How to reproduce
- Follow the "Quick Start" example for `graphql-hooks-ssr`
- Don't provide a `cache` options to `GraphQLClient`

### Suggested solution (optional)

- Update documentation to reflect that the `cache` option is required, or alternatively, update the [code](https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks-ssr/index.js#L16) to not actually require it.

**Comment by bmullan91** [comment]
We should throw an exception if `client.cache` is undefined.

**Comment by jackdclark** [comment]
Thanks for raising this @aribouius, we've updated the `graphql-hooks` and `graphql-hooks-ssr` packages to throw an error when `client.cache` isn't provided, explaining that it's required in SSR mode. We've also updated the relevant documentation. This has been released in the following patches:

- [graphql-hooks v3.3.1](https://github.com/nearform/graphql-hooks/releases/tag/graphql-hooks%403.3.1)
- [graphql-hooks-ssr v1.0.6](https://github.com/nearform/graphql-hooks/releases/tag/graphql-hooks-ssr%401.0.6)

@allcontributors[bot] please add @aribouius for bug
