### ISSUE TITLE
Add end to end tests

### ISSUE THREAD

**Issue by Joezo** [nearform/graphql-hooks#119]
### Package

All packages

### Description

Add end to end test using one of the example apps. We've been using [testcafe](https://github.com/DevExpress/testcafe) on other projects with some success, it should be fairly straight forward to set that up.

It would be great if we could, as part of a PR, build and deploy an example app and then run the tests against it. 

If we used the next.js example(would require bringing in to this repo), then we could use now.sh and it's github pull request feature. The other option is using Heroku's review apps with any of our examples.

**Comment by jackdclark** [comment]
@Joezo I think we should bring your Next.js example into this repo regardless of whether it's used for end to end tests.

**Comment by jackdclark** [comment]
The [create-react-app example](https://github.com/nearform/graphql-hooks/tree/master/examples/create-react-app) is now deployed with Netlify and we have PR apps enabled for that. The [react-browser-hooks](https://github.com/nearform/react-browser-hooks/blob/master/bin/acceptance.js) package runs `testcafe` against Netlify using [this script](https://github.com/nearform/react-browser-hooks/blob/master/bin/acceptance.js), where it waits for the Netlify preview deploy to succeed before running the acceptance tests against that preview app.

We probably want to run our tests against one of the apps that has SSR implemented though for the best coverage?

**Comment by Joezo** [comment]
Yeah I think I agree about it running agains an SSR example. Although anything is better than what we have now.

I'm going to pick this up now and try get something basic pointing at the `create-react-app` example.
