### ISSUE TITLE
Next.js example app

### ISSUE THREAD

**Issue by jackdclark** [nearform/graphql-hooks#12]
Implement an example app that uses this library, both SSR and in the browser with [Next.js](https://nextjs.org/)

**Comment by bmullan91** [comment]
This example app should live here: https://github.com/zeit/next.js/tree/canary/examples

**Comment by Joezo** [comment]
I have WIP example app over here https://github.com/Joezo/next.js/tree/with-graphql-hooks-example/examples/with-graphql-hooks

It's raised two things so far. Adjusting the variables passed into a query doesn't trigger a new request.

It might be nice to add something similar to Apollos `fetchMore` for pagination. The current solution in the example app is to just increase the size of the results coming back from the server, which just doesn't scale.

**Comment by Joezo** [comment]
I've opened a PR for this into the next.js repo https://github.com/zeit/next.js/pull/6482

**Comment by jackdclark** [comment]
This has been merged 🎉, nice work @Joezo. Closing.

**Comment by Stephen2** [comment]
Hey @Joezo @jackdclark will the example app work with SSR?
https://github.com/zeit/next.js/tree/canary/examples/with-graphql-hooks

**Comment by bmullan91** [comment]
@Stephen2 Sure does - it was a initially a clone of the `with-apollo` example, so the structure matches it but swaps out apollo with `graphql-hooks`.

Here's where @Joezo calls the `getInitialState` from `graphql-hooks-ssr` module: https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/with-graphql-client.js#L24

**Comment by Stephen2** [comment]
Thanks all, you are legends 👍 👍
