### ISSUE TITLE
useManualQuery returns state.loading=true by default

### ISSUE THREAD

**Issue by aribouius** [nearform/graphql-hooks#133]
### Package

`graphql-hooks`

### Environment
- `graphql-hooks` version: `3.3.1`

### Description
Calling `useManualQuery` currently returns a state with loading set to true, even though the request function has not been called.

### How to reproduce
- Call `useManualQuery`
- Inspect state

**Comment by Joezo** [comment]
@aribouius your fix has been released in 3.3.2. Thanks for contributing 🎉
