### ISSUE TITLE
README Updates

### ISSUE THREAD

**Issue by bmullan91** [nearform/graphql-hooks#138]
### Package

- [x] `graphql-hooks`

### Environment
- `graphql-hooks` version: `v3.2.3` after lerna

### Description

Publishing `README.md` only updates are tricky... The `~/packages/graphql-hooks/README.md` is ignored the changes are copied over during `prepublishOnly`.

Here's how I got it working:
1. Force a new version of `graphql-hooks`
`lerna version --conventional-commits --force-publish=graphql-hooks`
1. Publish to npm
`NPM_CONFIG_OTP=<code> lerna publish from-package`

### Proposed Changes

1. Leave things as-is but document steps in `CONTRIBUTING.md`
2. Change `~/packages/graphql-hooks/README.md` to only be a link to the top-level README
3. Move the top-level README into `~/packages/graphql-hooks`, change top-level one to be more overview / informational with links to sub-packages. Example https://github.com/ReactTraining/react-router

**Comment by jackdclark** [comment]
I think I'm in favour of 3. Top level overview with a quick start guide and links to packages and examples. Then full API documentation and guides moved into `packages/graphql-hooks`.

**Comment by bmullan91** [comment]
Ditto @jackdclark 👍
