### ISSUE TITLE
Inconsistent results for changing query

### ISSUE THREAD

**Issue by kkogovsek** [nearform/graphql-hooks#150]
### Package
`graphql-hooks`

### Environment

- `graphql-hooks` version: 3.4.0
- `react` version: 16.8.4
- Browser: Any

### Description

When a query changes quickly results are inconsistent. What's wrong is that the current query is not tracked inside useClientRequest.js resulting in a race between different queries and the last one will be stored in state. In my case having consistent timing of server that means if I click next multiple times, I will see loading state at first and then multiple UI updates. Also, the loading state is lost since there's some of the old data in the state which arrived after all loading actions have been dispatched.

### How to reproduce

I created a simple code sandbox where you can click next/prev multiple times and see the issue in action.
https://codesandbox.io/s/mj6m8yvv4p

### Suggested solution (optional)

If this is undesired behavior I would like to open a PR solving that.

**Comment by bmullan91** [comment]
@kkogovsek Good catch - we'd love to see a PR if you're up for it 🤗

**Comment by bmullan91** [comment]
@kkogovsek Thanks again - the fix is now available in `graphql-hooks@3.4.1` 🎉
