### ISSUE TITLE
Add useDebugValue

### ISSUE THREAD

**Issue by kkogovsek** [nearform/graphql-hooks#151]
### Description

I would like this package to add useDebugValue to hooks and make them simple to track in dev tools. I think just showing Loading/Loaded/Error would be enough for useQuery to give a user a sense of what's going on with a hook. Current implementation gives out a few nested hooks without showing relevant data (that's how dev tools are with complex data), so just showing a status would be an improvement. 

### Suggested implementation

I can implement that upon discussion and send a PR.

**Comment by bmullan91** [comment]
@kkogovsek Interesting - we could add another option `debug: Boolean` to all the hooks. Then inside the `useClientRequest` hook, we could log out the various states - like a redux logger. Was that what you had in mind?

**Comment by bmullan91** [comment]
@allcontributors add @kkogovsek for bug and ideas.

**Comment by kkogovsek** [comment]
@bmullan91 I like your idea but what I had in mind was to use *useDebugValue* hook which integrates with react dev tools and offer a quick preview of what's going on inside hooks. Here are screenshots of what I ment.
<img width="338" alt="Screenshot 2019-03-20 at 13 24 42" src="https://user-images.githubusercontent.com/8089644/54684154-c4d0f080-4b13-11e9-9b2f-357c6b54d7be.png">
<img width="245" alt="Screenshot 2019-03-20 at 13 25 11" src="https://user-images.githubusercontent.com/8089644/54684165-c8647780-4b13-11e9-81b7-3168cf5687e4.png">
<img width="238" alt="Screenshot 2019-03-20 at 13 25 23" src="https://user-images.githubusercontent.com/8089644/54684166-ca2e3b00-4b13-11e9-95bb-52d48ea6a737.png">

**Comment by bmullan91** [comment]
@kkogovsek Ah sorry - now I get you. Makes sense 👍
