### ISSUE TITLE
Add ability to skip query entirely

### ISSUE THREAD

**Issue by ckiss** [nearform/graphql-hooks#154]
### Description

In some cases one could skip making the request to graphql if some condition is true. For example if you have two cascade dropdowns on initial render you want to load and display data only in the first one and the second one just display it as disabled. When you pick something in the first dropdown you have to query the data for the second dropdown.

In this example the second dropdown will skip making the request to get the data until the condition to have selected some value in the first dropdown is met.

### Suggested implementation

A `skip` boolean prop could be set as part of `useQuery` `opts` and if true the entire query will be skipped and it will return `data` as undefined

**Comment by reverie** [comment]
Why should logic this be in the graphql client library rather than application code?

**Comment by danielbischoff** [comment]
You can easily use useManualQuery for that.
With skip, the return type of data can be undefined like you said, but now everyone has to check if data is present before accessing it.

**Comment by edvinasbartkus** [comment]
Agree on @danielbischoff here. Skipping can be achieved with `useManualQuery`. here is a quick example:

```js
const { data } = useQuery(INITIAL_DROPDOWN_QUERY)
const [fetch, { data: subData = [] }] = useManualQuery(SECONDARY_DROPDOWN_QUERY)

const onSecondaryDropdown = () => {
  fetch()
  ...
}
```
In this example, subData by default will be undefined but you can assign a default value with destructing the object and it will replace with the actual value once you call `fetch`. Hopefully, this can work for you.

Closing this now. Let us know if you see that there is another benefit of having `skip`.

**Comment by JaKXz** [comment]
This is a feature that I think is very useful from react-apollo mainly because you might have dependent queries in a single component. Maybe I'm doing something wrong, but, if `useQuery(QUERY_STRING, { skip: !someRequiredVariable })` returns `{ loading: true, error: null, data: null }` when `someRequiredVariable` is falsy, then it makes sequential operations very easy to write. For example:

```js
function MyComponent({ ...props }) {
  const randomData = somePromiseApi();
  const { loading, error, data } = useQuery(`query { ... }`, { 
    skip: !randomData.present 
  });

  if (loading) {
    return <Loading />;
  }

  if (error) {
    return <Error />;
  }

  return <div>{data}</div>;
}
```

In this example, the query should never be requested until the promise API returns with a value for the `.present` property, and the `<Loading />` component will be shown until the data or an error comes back.

Does this seem reasonable?

**Comment by bmullan91** [comment]
@JaKXz `useManualQuery` is more suitable for that use case since you only want to call it after the usePromiseApi has resolved. NOTE I'd recommend you use either a hook for the promise call, or a `useEffect`.

**Comment by jampy** [comment]
I think the requested feature would be very useful in certain situations. 

A slightly modified example:

```jsx

function EditOrCreateUserComponent({ userId }) {

  const { loading, error, data } = useQuery(USER_QUERY, {
    variables: {
      userId
    },
    skip: !userId
  });

  if (loading) {
    return <Loading />;
  }

  if (error) {
    return <Error />;
  }

  return <EditUserForm
    initialData={userId ? data.userDetails : null}
  />;

}

```

...with <EditUserForm> being some sort of form that allows entering user details.

Needing to resort to `useManualQuery()` forces to recreate parts of `graphql-hooks` IMHO, while I think it would be trivial to implement in `useQuery()` itself..

Let me know ifi you see a better way to implement the example.

See also https://stackoverflow.com/questions/59489097/use-query-hook-react-apollo-conditional-call/59489673 and https://www.apollographql.com/docs/react/api/react/hooks/#options
