### ISSUE TITLE
Discuss, Slack...Discord channel :D 

### ISSUE THREAD

**Issue by ouuyeah** [nearform/graphql-hooks#157]
Maybe some tool to spread love, this library is great and I think will have future, please make some chat around :)

Also, somebody has a NextJs boilerplate to share with graphql-hooks :v ?
Thanks guys, you're doing a great thing here.

**Comment by bmullan91** [comment]
Thanks, @ouuyeah 🤗- great idea, I've created a spectrum community - it seems to be the new hotness.

Community: https://spectrum.chat/graphql-hooks - this is _brand new_ btw
Next.js example: https://github.com/zeit/next.js/tree/canary/examples/with-graphql-hooks
