### ISSUE TITLE
Docs: Keep data from previous fetch

### ISSUE THREAD

**Issue by reiv** [nearform/graphql-hooks#172]
### Description

Let's say `useQuery` is called based on the live contents of an input field (e.g. a filter/search box). By default, `data` gets set to `undefined` when the query arguments change, causing rendered content to flash in and out of existence – this doesn't look good. In order to keep the state from the previous fetch, `updateData` needs to be specified in the `useQuery` options (can be as trivial as `{ updateData: (data, nextData) => nextData }`), but that's a bit unintuitive because it doesn't really explain what is actually happening under the hood (`RESET_STATE` isn't fired), and I'm not actually doing anything useful with `updateData`, like pagination.
https://github.com/nearform/graphql-hooks/blob/2c3f359acf2bef88cc26a361f89541391a1d6a48/packages/graphql-hooks/src/useClientRequest.js#L79-L81

I'm not sure if this is a common enough use case to warrant any changes, but it might be worth adding to the docs that this is what setting `updateData` does.

**Comment by bmullan91** [comment]
@reiv Yea there are a couple of ways to handle this:

1. Use `refetch` return from `useQuery`, and when the input changes call it with the new variables. This already includes the pass-through `updateData` function.
2. Use `useManualQuery` and handle the state changes yourself

I'd also recommend debouncing the input `onChange` handler that causes the query to be triggered.
