### ISSUE TITLE
Show warning when using gql or passing in non-strings

### ISSUE THREAD

**Issue by good-idea** [nearform/graphql-hooks#197]
### Description

I was migrating from Apollo and didn't remove `gql` before my query strings. The API I was querying returned some cryptic responses and it took a while to figure out that `gql` was causing the problem. The docs for graphql-hooks say "No need to wrap the query in `gql`", but it's easy to miss.

### Suggested implementation

Perhaps showing a warning in the console telling the developer to pass the query as a plain string? And, maybe notes in the docs that highlight that you should *not* use `gql` instead of "don't need to".

I'm happy to open a PR for this, just let me know how you'd like it to go!

**Comment by bmullan91** [comment]
@good-idea Good idea 😜 A PR would be much appreciated!

**Comment by good-idea** [comment]
No problem. How would you like to have it go? Just warn when it's not a string?

**Comment by bmullan91** [comment]
Fixed in #199 and available in `graphql-hooks@3.4.2`

**Comment by dohomi** [comment]
@bmullan91 would it not be better to use `print` function of `graphql/language/printer` to parse `gql` in case GQL is passed instead of a string?
