### ISSUE TITLE
Should react-dom/server be bundled in the Next.js example app?

### ISSUE THREAD

**Issue by alexparish** [nearform/graphql-hooks#204]
### Package

`graphql-hooks-ssr`

### Environment

- `graphql-hooks` version: 3.4.2
- `graphql-hooks-ssr` version: 1.1.1
- `graphql-hooks-memcache` version: 1.2.0
- `react` version: 16.8.6
- Browser: All

### Description

In the [Next.js example app](https://github.com/zeit/next.js/tree/canary/examples/with-graphql-hooks) it appears `react-dom-server.browser.production.min.js` is bundled into `commons.xxxx.js`.

<img width="838" alt="Screenshot 2019-04-09 at 09 48 31" src="https://user-images.githubusercontent.com/135674/55786686-a9228f80-5aac-11e9-97d2-dc04fa20a306.png">

This adds over 20kB to the commons file:

<img width="548" alt="Screenshot 2019-04-09 at 09 48 53" src="https://user-images.githubusercontent.com/135674/55786712-b6d81500-5aac-11e9-9f1b-3f31ce5de7ef.png">

Is this file needed client-side? What is it doing? It may well be my lack of understanding of the project setup but I wanted to check.

If it is not needed - if it's being included accidentally for example - the amount of JavaScript deployed to the client could be reduced and page load performance improved.

### How to reproduce

Clone the [Next.js example app](https://github.com/zeit/next.js/tree/canary/examples/with-graphql-hooks) and execute the `npm run build` command. You'll see `react-dom-server.browser.production.min.js` in the commons file.

**Comment by bmullan91** [comment]
@alexparish Interesting, I think this is an issue with either next.js itself / how the project is configured. I couldn't find any references to `react-dom/server` in our example 🤔

**Comment by alexparish** [comment]
@bmullan91 Possibly, although I couldn't see it being bundled in the [hello-world app](https://github.com/zeit/next.js/tree/canary/examples/hello-world)

**Comment by bmullan91** [comment]
@alexparish Next thing to try: update all the deps (next, graphql-hooks, react etc) and re-check. This would be a good first PR to the next repo too if you're up for it :)

**Comment by alexparish** [comment]
@bmullan91 will do

**Comment by alexparish** [comment]
Figured out how to exclude that `graphql-hooks-ssr` package from the client-side bundle in a Next.js app.

Simply add the following to package.json:

```
"browser": {
    "graphql-hooks-ssr": false
}
```

Apparently webpack takes that `browser` field into account when working out what to bundle :+1:

Closing this issue as it's not a problem with the `graphql-hooks` library itself.

**Comment by alexparish** [comment]
@bmullan91 I've created a PR that includes this change: https://github.com/zeit/next.js/pull/7015

It reduces the commons chunk by 18.8kB (7kB gzipped)

I also removed the next config that configured serverless mode as this was preventing the app from building.

**Comment by bmullan91** [comment]
@alexparish thanks 🙇
