### ISSUE TITLE
[Question] How to update cache without refetch

### ISSUE THREAD

**Issue by shashkovdanil** [nearform/graphql-hooks#205]
### Package

`graphql-hooks`
`graphql-hooks-ssr`
`graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: `^3.4.1`
- `graphql-hooks-ssr` version: `^1.2.0`
- `graphql-hooks-memcache` version: `^1.1.0`
- `react` version: `^16.8.6`

### Description

How to update cache without refetch? In all examples, after a mutation, a refetch is triggered.

**Comment by bmullan91** [comment]
@shashkovdanil Check out https://github.com/nearform/graphql-hooks/issues/52 - the various options are being discussed there.
