### ISSUE TITLE
How to use GraphQLClient in both SSR and Client mode for Next.Js app?

### ISSUE THREAD

**Issue by resdevd** [nearform/graphql-hooks#219]
### Package

- [ ] `graphql-hooks`
- [ ] `graphql-hooks-ssr`
- [ ] `graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: 3.5 
  
- `graphql-hooks-ssr` version: current
- `graphql-hooks-memcache` version: current
- `react` version: latest
- Browser: all

### Description

Can anyone help me with below situation? 
I'm using a Graphql server in a docker container and next's node app in another container.

I’m using Traefik on top of this and routed Graphql server as **api.website.com/graphql** and next’s app as **website.com**. 

I followed example according to 
https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/init-graphql.js

```
import { GraphQLClient } from 'graphql-hooks'
import memCache from 'graphql-hooks-memcache'
import unfetch from 'isomorphic-unfetch'

let graphQLClient = null

function create (initialState = {}) {
  return new GraphQLClient({
    ssrMode: !process.browser,
    url: 'https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn',
    cache: memCache({ initialState }),
    fetch: process.browser ? fetch.bind() : unfetch // eslint-disable-line
  })
}

export default function initGraphQL (initialState) {
  // Make sure to create a new client for every server-side request so that data
  // isn't shared between connections (which would be bad)
  if (!process.browser) {
    return create(initialState)
  }

  // Reuse client on the client-side
  if (!graphQLClient) {
    graphQLClient = create(initialState)
  }

  return graphQLClient
}
```

I deployed my app into production replacing above url with **api.website.com/graphql**
Everything is working fine, however the website is pretty slow. I’m assuming using **api.website.com/graphql** is causing this (I guess it has to a roundtrip with dns even though they both are located in the same server?), as I didn’t have this problem in DEV when using **localhost:8000/graphql** .
Now I’m stuck at how to edit the above init Graphql hook file.
Should I be using two create functions? One with docker localhost url when !process.browser and with api.website.com url when its browser? 
Is it gonna screw up entire Graphql config for website? Can anyone give me some pointers? My bad if this question is ignorant. Thanks

**Comment by resdevd** [comment]
I finally ended up with the following ini-graphql.js code and performance is greatly improved. This was result of trial and error an dI'm not sure if this is the right way. Can anyone take a look into the following code and see if there is something problematic using graphql-hooks in SSR in this manner from the example ?
 ( https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/init-graphql.js )
( https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/with-graphql-client.js )


```
import memCache from 'graphql-hooks-memcache'
import unfetch from 'isomorphic-unfetch'

let graphQLClient = null

function create (initialState = {}) {
    return new GraphQLClient({
        ssrMode: !process.browser,
        url: 'http://docker-localhost/graphql',
        cache: memCache({ initialState }),
        fetch: process.browser ? fetch.bind() : unfetch // eslint-disable-line
    })
}

function clientCreate (initialState = {}) {
    return new GraphQLClient({
        ssrMode: !process.browser, 
        url: 'https://api.website.com/graphql',
        cache: memCache({ initialState }),
        fetch: process.browser ? fetch.bind() : unfetch // eslint-disable-line
    })
}

export default function initGraphQL (initialState) {
    // Make sure to create a new client for every server-side request so that data
    // isn't shared between connections (which would be bad)
    if (!process.browser) {
        return create(initialState)
    }
    
    // Reuse client on the client-side
    if (!graphQLClient) {
        graphQLClient = clientCreate(initialState)
    }
    
    return graphQLClient
}
```

Note that https://api.website.com/graphql and http://docker-localhost/graphql are from same server, one is externally exposed api and second one is internal.

**Comment by bmullan91** [comment]
@resdevd Another approach would be to pass in a different `fetch` option when creating the client on the server. For example, if the graphql API and react app live on the same server you can call the graphql API directly. It will require returning a fake `Response` for the graphql client to handle it without noticing.

We could probably make this a separate module `graphql-hooks-schema-fetch` or include it as a named export in `graphql-hooks-ssr`


### Usage
```js
const { schemaFetch } = require('graphql-hooks-ssr')
const schema = require('./path/to/your/schema')

const client = new GraphQLClient({
    cache: memCache(),
    fetch: schemaFetch({ schema })
  })
```

### Possible Implementation

```js
function schemaFetch({ schema }) {
  return function fetch(url, options) {
    // extract the operation from options.body
    // execute the opteration
    // return a promise which resolves a fake `Response` object 
  }
}
```

@resdevd Let me know your thoughts on this, and if you'd be interested in helping out :)

**Comment by resdevd** [comment]
@bmullan91 I'll be honest, I'm not that knowledgeable or skilled with implementation of graphql-ssr, I play by ear with a lot of trial and error. I'm satisfied with the performance of my website with above change which greatly improved the load speed to under 3 seconds from 6-7 seconds.

**Comment by dcorb** [comment]
Check the official Next.js example for an official implementation of the pattern:  https://github.com/vercel/next.js/blob/canary/examples/with-graphql-hooks/lib/graphql-client.js
