### ISSUE TITLE
Support for interceptors

### ISSUE THREAD

**Issue by pelletiermaxime** [nearform/graphql-hooks#237]
Is there support for interceptors/middlewares in this package ? 
Those would really be useful for implementing JWT auth. For example using axios interceptors you can do this: https://gist.github.com/alfonmga/96474f6adb6ed8dee8bc8bf8627c0ae1.

Another sample implementation is react-fetching-library: https://marcin-piela.github.io/react-fetching-library/#/?id=request-interceptors.

Thanks!

**Comment by bmullan91** [comment]
Hey @pelletiermaxime,

We don't have anything like that in place, you can, however, set headers on the client in a couple of different ways:

```js
// during bootup
const client = new GraphQLClient({
  url: '...',
  headers: {
    jwt: '...'
  }
})

// later / somewhere else in your app
// e.g. after login

import React, { useContext } from 'react'
import { ClientContext } from 'graphql-hooks'

function MyComponent() {
  const client = useContext(ClientContext)

  client.setHeader('jwt', 'value')
}
```

**Comment by edvinasbartkus** [comment]
You can look at the option of supplying axios instance for fetch functionality where you can control interceptors. Here is the example document in README.md:
https://github.com/nearform/graphql-hooks#request-interceptors

For now, will be closing this issue.

**Comment by pelletiermaxime** [comment]
Cool, thanks!
