### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by yo34** [nearform/graphql-hooks#240]
Is the credentials supported, I use 

const client = new GraphQLClient({url: 'http://localhost:30000/graphql', credentials: "same-origin"})

But it's not seem to work.

**Comment by bmullan91** [comment]
Hi @yo34,

`credentials` is an option used by `fetch` - we support those options via `fetchOptions` object passed to `GraphQLClient`:

```js
const client = new GraphQLClient({
  url: '/graphql',
  fetchOptions: {
    credentials: 'same-origin'
  }
})
```

**Comment by yo34** [comment]
Hi @bmullan91,
It works !
Thanks you.
