### ISSUE TITLE
setHeader not working

### ISSUE THREAD

**Issue by emersonlaurentino** [nearform/graphql-hooks#258]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: `3.5.0`
- `react` version: `16.8.6`
- Browser: `Chrome 73.0.3683.86 64 bits`

### Description

The Authorization header is not being defined in the query, even I have already defined it previously.

### How to reproduce

App.tsx
```jsx
const App: React.FC = () => {
  useEffect(() => {
    const token = localStorage.getItem(AUTH_TOKEN)
    const authorizationHeader = `Bearer ${token}`

    if (token) {
      client.setHeader('Authorization', authorizationHeader)
    }
  }, [])

  return (
    <ThemeProvider>
      <ClientContext.Provider value={client}>
        <Router>
          <PrivateRoute path="/editor" exact component={Editor} />
          <Route path="/login" exact component={Login} />
        </Router>
      </ClientContext.Provider>
    </ThemeProvider>
  )
}
```
PrivateRoute.tsx

```jsx
const PrivateRoute: React.FC = props => {
  const { loading, error } = useQuery(CURRENT_USER_QUERY)

  if (loading) {
    return null
  }

  if (error) {
    return <Redirect to="/login" />
  }

  return <>{props.children}</>
}
```

**Comment by bmullan91** [comment]
@emersonlaurentino try moving the client setHeader out of the useEffect or do it when you create the client. I pretty sure any requests after your setHeader call will have the correct header, it’s just that the initial render won’t since the logic is in a useEffect and nothing has caused a re-render.

**Comment by emersonlaurentino** [comment]
@bmullan91 worked correctly, thank you.

I was using `fetchOptions` to override the headers as a way to work around this problem.
