### ISSUE TITLE
Add support for GraphQL multipart requests

### ISSUE THREAD

**Issue by olistic** [nearform/graphql-hooks#261]
### Description

Add support for GraphQL multipart requests following the [spec](https://github.com/jaydenseric/graphql-multipart-request-spec). This would allow to upload files with a GraphQL mutation.

### Suggested implementation

Use the [extract-files](https://github.com/jaydenseric/extract-files) package and follow an approach similar to [this](https://github.com/jaydenseric/graphql-react/blob/dfe7883850cb07e2a3f3ca38280db77e1d6f364d/src/universal/graphqlFetchOptions.mjs) in [here](https://github.com/nearform/graphql-hooks/blob/df6ee62cd7a81c079ec3d8f688514b7a287b8372/packages/graphql-hooks/src/GraphQLClient.js#L103).

Let me know what you think and I'll get started!

**Comment by pelletiermaxime** [comment]
9 hours ago ? I just started looking at how file upload works with this package. I will be the first to test your implementation when you get it working =)

**Comment by bmullan91** [comment]
@olistic, By all means, go for it 🙌
