### ISSUE TITLE
Docs: Fragments Guide

### ISSUE THREAD

**Issue by bmullan91** [nearform/graphql-hooks#27]
Demonstration how you can use & combine GraphQL fragments via template strings

**Comment by altano** [comment]
Hey! Does using fragments **just** need documentation, or is it not working yet and there's work left to be done?

**Comment by bmullan91** [comment]
@altano Just docs required - it's just combining template strings, perhaps documenting some best practices.

**Comment by altano** [comment]
If you link me to a code example of any kind I could maybe figure it out and help write a draft of the docs? No rush. Thanks!

**Comment by altano** [comment]
And I certainly hope you don't _actually_ mean it's _just_ template string concatenation of strings like:

```
const userFragment = graphql`
  name
  profileUrl
`;
const query = graphql`
  query Users {
    edges {
      node {
        ${userFragment}
      }
    }
  }
```

This might be fine for a REALLY tiny site but it would obviously have all sorts of issues like debuggability. For example, if the query ended up being invalid you'd have no way of knowing where the problematic code actually was. And you'd have to pass all data from the entire response to all components.

**Comment by matepaiva** [comment]
Hey, is there any possible timeframe for the fragment documentation? I can't help because I have never used graphql-hooks. Actually I am considering migrating from relay to here, but I don't know if it is a good Idea, mainly because of how relay deals with fragments.

**Comment by simoneb** [comment]
When this issue was created, fragments were probably not as common as they are now. I don't think we need docs for that as there is nothing special that this library is going to support fragments, they are simply part of GraphQL and hence available in any implementation. I'm going to close this issue.

**Comment by matepaiva** [comment]
Fair enough :)
