### ISSUE TITLE
Add pagination helper

### ISSUE THREAD

**Issue by Joezo** [nearform/graphql-hooks#29]
Whilst implementing an example app in next.js it occurred that pagination is pretty complicated and could be simplified by `useQuery` offering a method to help load more data and update the existing data without having to refetch everything each time.
Apollo does this with a `fetchMore` method https://www.apollographql.com/docs/react/features/pagination.html#fetch-more

**Comment by jackdclark** [comment]
I currently have two draft implementations for this:

- #42 A `fetchMore` function, similar to apollo
- #41 A more declarative version where the consumer chooses how the result merges with the previous result

Both use the same result updater implementation.

@bmullan91 @Joezo interested in your thoughts on which is a better API?

**Comment by jackdclark** [comment]
After speaking to @Joezo, a third approach (See https://github.com/nearform/graphql-hooks/pull/44) is a merge of the two approaches #42 & #41.
