### ISSUE TITLE
How to refresh JWT token for every 401 error and retry the query again

### ISSUE THREAD

**Issue by kinyat** [nearform/graphql-hooks#308]
### Package

- [x] `graphql-hooks`

### Environment

- `graphql-hooks` version: 3.5.1

### Description

Hi,

Thanks for making this awesome repo for graphql hooks!

We are trying to implement a JWT based auth and want to see how graphql-hooks fits it.

We see there is an API called `client.setHeader` which can be used to set the `Authorization` header.

However, we want to have some kind of mechanism for `graphql-hooks` to handle all 401 unauthorized error. If it happens, we want to refresh the JWT token with the refresh token, update the access key and then retry the query. Only if that fails then it redirects the user to a login page.

In Apollo, we can do this by setting up a custom fetch (see: https://medium.com/@lucasmcgartland/refreshing-token-based-authentication-with-apollo-client-2-0-7d45c20dc703).

Is there anything similar we can do in `graphql-hooks`, please?

Many Thanks!

**Comment by edvinasbartkus** [comment]
`graphql-hooks` also supports custom `fetch`. It can be passed into `GraphQLClient` constructor as `fetch` property. I did a quick experiment to validate that it works with custom axios where you can setup interceptor to capture JWT expired response and update token, here is the example:

```js
import axios from 'axios'
import { buildAxiosFetch } from '@lifeomic/axios-fetch'
import { GraphQLClient } from 'graphql-hooks'

const gqlAxios = axios.create()
gqlAxios.interceptors.response.use(function (response) {
  return response
}, function (error) {
  // Handle expired JWT and refresh token
})

const client = new GraphQLClient({
  url: '/graphql',
  fetch: buildAxiosFetch(gqlAxios)
})
```

**Comment by mcollina** [comment]
Maybe we can add that as a snippet in the README?

**Comment by edvinasbartkus** [comment]
@kinyat let us know if there are any troubles getting it to work with JWT and we will try to address it. For now, will be closing this.
