### ISSUE TITLE
Shouldn't refetch clear errors?

### ISSUE THREAD

**Issue by olistic** [nearform/graphql-hooks#313]
### Description

I'm using `refetch` to retry a failed query, like this:

```js
const List = () => {
  const { loading, error, data, refetch } = useQuery(MY_LIST_QUERY)

  if (loading || error) {
    return <Loading error={error} retry={refetch} />
  }

  // ...
}

const Loading = ({ error, retry }) => {
  if (error) {
    return <button onClick={retry}>Retry</button>
  }

  return <Spinner />
}
```

I expect that when I click "Retry" (which calls `refetch`) `loading` is set back to `true` and any errors from previous fetch are cleared, so I see the spinner again.

Does this make sense?

**Comment by olistic** [comment]
@edvinasbartkus Were you able to take a look at this? Thanks

**Comment by bmullan91** [comment]
@olistic Sorry for the delay, yea I think you're right - we should clear the errors.

In the meantime, you can handle them as two separate states:

```js
if (loading) {
  return <Loading />
}

if (error) {
  return <Loading error={error} retry={refetch} />
}
```

I think you're overloading the `Loading` component here btw, might be worth having a separate component/logic for handling errors.

**Comment by edvinasbartkus** [comment]
Sorry for the delay. Some vacation time got on a way. I have looked it up the changes I have prepared earlier and rebased with the current master:
https://github.com/nearform/graphql-hooks/pull/339

My suggestion is simply to check before going to loading state if there was an error before. If so, we can reset to the initial state + loading.
