### ISSUE TITLE
Client URL override

### ISSUE THREAD

**Issue by joeynimu** [nearform/graphql-hooks#315]
### Description

It would be nice to have a way to override the `url` passed on the client's constructor. 

For instance, I have two `graphql` endpoints. One that doesn't need `Authorization/Authentication` and another that doesn't. Some parts of my app use data that doesn't need an access token and other parts consume data that doesn't.

Of course I could create two instances on the client with the two different URL's but that would been than instead on wrapping the provider on the top most node of my app, I'd need to wrap the components that are consuming the data individually which might be a lot of work.

### Suggested implementation

Similar like we have `client.setHeaders(headers)`: which replaces the value of `client.headers`; something like `client.setUrl(url: String)`? 

Thanks.

**Comment by galmail** [comment]
In this case, my suggestion will be doing something like this:

1. Create two clients, one of which is using Auth settings.

```
const guestClient = new GraphQLClient({
  // no-auth-required settings
})
const loggedClient = new GraphQLClient({
  // auth-required settings
})
```

2. Create an HOC function to wrap your components like this:

```
function addClientContextProvider(WrappedComponent, client) {
    return class extends React.Component {
        constructor(props) {
            super(props)
        }
        render() {
            return (
                <ClientContext.Provider value={client}>
                    <WrappedComponent {...this.props} />
                </ClientContext.Provider>
            )
        }
    }
}
```

3. Finally you can use it in your code like this:

```
const GuestComponent = addClientContextProvider(ComponentA, guestClient)
const LoggedComponent = addClientContextProvider(ComponentB, loggedClient)
```
