### ISSUE TITLE
throw errors from hooks

### ISSUE THREAD

**Issue by capaj** [nearform/graphql-hooks#324]
same reasoning as in https://github.com/trojanowski/react-apollo-hooks/issues/28

**Comment by machineghost** [comment]
I'd settle for "do one or the other, but do it consistently!"  Right now I'm getting an error when I try to call the function returned from `useMutation`.  It *does not* return an error object, but an error in the process somehow results in an uncatchable error being thrown (not even my dev tools "pause on exceptions" can catch it!).

Ultimately, if you're going to make "we return the errors as values" as the way the library works, you need do that 100% of the time.  If you're not, you should just throw errors like a normal library.

**Comment by machineghost** [comment]
P.S. I just tried the library's **fourth** error handling mechanism (seriously, all I want is one that works).  I added an `onError` property to my `GraphQLClient` instantiation, and ... it failed to catch the error also.

**Comment by machineghost** [comment]
P.P.S. The ultimate problem wound up being that I was passing a `variables` object that was just `{}` (and that violated god knows what on the server).  But, suffice it to say that it's sub-optimal to take half an hour to track down an empty `variables`, and that a single consistent error handling mechanism (ie. one that works 100% of the time) would have saved me that half hour.

**Comment by simoneb** [comment]
Have you tried using the [`onError` handler](https://github.com/nearform/graphql-hooks#graphqlclient)? We're using a similar approach [here](https://github.com/nearform/brokeneck/blob/master/packages/brokeneck-react/src/hooks/useGraphQLClient.js) (you'll have to browse around the codebase a bit to see how it works exactly) and though not supported by the library out of the box there is a way to do both local and global error handling.

**Comment by YuriFontella** [comment]
Hello, taking this issue for a doubt.

The same way I can catch the error that comes from the server through the onError in the instance...

```
const graphQLClient = new GraphQLClient({
  url: process.env.GRAPHQL,
  onError({ operation, result }) {
    console.log(result.error.graphQLErrors)
  }
})
```

can I see this error through the context using the useContext?

```
import React, { useContext } from 'react'
import { ClientContext } from 'graphql-hooks'

function MyComponent() {
  const client = useContext(ClientContext)
  
  console.log(client.error.graphQLErrors)
}
```

Hello, taking this issue for a doubt.

The same way I can catch the error that comes from the server through the onError in the instance, can I see this error through the context using the useContext?

I didn't understand the real use of `client.logErrorResult`, if it's just to create a custom error or if it really brings the errors of the client instance.

If you can show an example, thank you.

**Comment by YuriFontella** [comment]
Hello, taking this issue for a doubt.

The same way I can catch the error that comes from the server through the onError in the instance...

```
const graphQLClient = new GraphQLClient({
  url: process.env.GRAPHQL,
  onError({ operation, result }) {
    console.log(result.error.graphQLErrors)
  }
})
```

can I see this error through the context using the useContext?

```
import React, { useContext } from 'react'
import { ClientContext } from 'graphql-hooks'

function MyComponent() {
  const client = useContext(ClientContext)
  
  console.log(client.error.graphQLErrors)
}
```

I didn't understand the real use of `client.logErrorResult`, if it's just to create a custom error or if it really brings the errors of the client instance.

If you can show an example, thank you.

**Comment by simoneb** [comment]
@capaj @machineghost @YuriFontella I've created a first working implementation for this feature. I would appreciate your feedback before going forward with it.

#665
