### ISSUE TITLE
Enforce conventional commit messages

### ISSUE THREAD

**Issue by Joezo** [nearform/graphql-hooks#325]
### Description
We should use automated tools to help prevent PRs being merged with non conventional commits.

### Suggested implementation
We've had success with a combination of these two tools in the past.
- [semantic release pull requests](https://github.com/probot/semantic-pull-requests) 
- [commitlint](https://github.com/conventional-changelog/commitlint).

**Comment by galmail** [comment]
@mcollina for https://github.com/probot/semantic-pull-requests I will need access

**Comment by mcollina** [comment]
Enabled.
