### ISSUE TITLE
Issue in Edge Causing JS Parsing Error

### ISSUE THREAD

**Issue by joealden** [nearform/graphql-hooks#331]
### Package

`graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: `3.6.0`
- `graphql-hooks-memcache` version: `1.2.1`
- `react` version: `16.8.6`
- Browser: Edge 18

### Description

When visiting my site in Edge, I am getting the following error logged to the console:

```
SCRIPT1028: Expected identifier, string or number
```

From a little research, and from looking at where the error happened in the source-map (shown in the below screenshot), I think this is happening because [object spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals) is being used, and is not getting compiled down to code Edge can understand (Edge currently doesn't support the object spread syntax :cry:).

![screenshot](https://user-images.githubusercontent.com/10297243/61335814-bf1bbb00-a826-11e9-99c2-81f2014a2cf3.png)

### How to reproduce

Create a project that uses `graphql-hooks-memcache`, then try to load the site in Edge.

### Suggested solution

If my assumptions are correct about the cause of the issue, either compile the syntax down to syntax Edge understands, or change the source to not use the object spread syntax at all.

---

Thanks for your time!

**Comment by mcollina** [comment]
How are you bundling/transpiling this? I fear it might just be some missing configuration on webpack/babel.

**Comment by joealden** [comment]
@mcollina I am using a relatively new version of GatsbyJS, but a version before they started transpiling `node_modules` (I haven't upgraded due to a build issue we are having with our project with the latest version).

From your above comment, am I right in thinking that you expect people to configure webpack + babel to transpile their project's dependencies?

**Comment by bmullan91** [comment]
@joealden Good catch! Seems we're missing this `.babelrc.js` in `graphql-hooks-memcache`, I'm hopefull using the same one from here should do the trick: https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/src/.babelrc.js

@joealden I don't have easy access to a windows machine to test/debug, do you fancy trying that out?

Steps:
1. Read the `for developers` section in the contributing guide: https://github.com/nearform/graphql-hooks/blob/master/CONTRIBUTING.md#for-developers
1. Copy `babelrc.js` from `packages/graphql-hooks/src` into `packages/graphql-hooks-memcache`
1. `npm run build` inside `packages/graphql-hooks-memcache`
1. `npm pack` inside `packages/graphql-hooks-memcache`
1. In your test repo, you can now `npm install path/to/graphql-hooks-memcache-1.X.X.tgz`

**Comment by WayneEllery** [comment]
I can confirm that this would fix this particular issue. We are experiencing the same issue. @bmullan91 Are you able to make the change or I can create a PR?

**Comment by bmullan91** [comment]
@WayneEllery thanks, send us a PR that'd be great 🙇
