### ISSUE TITLE
Refetch Causes Component Reload

### ISSUE THREAD

**Issue by Saintroi** [nearform/graphql-hooks#333]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 3.6.0
- `graphql-hooks-memcache` version: 1.2.1
- `react` version: 16.8.6
- Browser: Chrome

### Description

I am updating my application to focus on hooks usage, and in the process I wanted to try and replace the GraphQL calls with hooks as well.

I have a component that displays a list of users, and other components with forms that allow creation, editing and removal of those users. I pass the refetch function from the query that gets the list of users down to the other components for them to call after performing a mutation.

With the Apollo tools for querying, this refetch call simply re-populates the list of users without any re-loading of the component or page (no flash or time where there are no users in the list)

However, with this plugin the refetch function seems to re-load the entire component resulting in a momentary blank area where the component should be. This occurs regardless of if I call it from that component or if I pass it to another component to call after a mutation.

### How to reproduce

Refetch a query, watch the component reload.

I figure you guys might be aware of this, maybe it's related to #52 but I wasn't totally sure.

**Comment by bmullan91** [comment]
@Saintroi sorry for the delay; do you might including a code example of this issue you're describing? I think we can solve your issue with the current API :)

**Comment by Saintroi** [comment]
Sure! Code is below, just to confirm I added a "refetch" button on my page that calls the refetch for the LIST_USERS query, which then causes the entire component to reload.

Typically I'd be passing this refetch down to a create/delete/update user component and calling it once those actions have been taken, so want to avoid what is essentially a page refresh.

Thanks!

```js
function ListUser(props) {

  const [searchQuery, setSearchQuery] = useState('');
  const search = React.createRef();

  function handleSearchChange(event) {
    setSearchQuery(event.target.value);
    search.current.focus();
  }

  function handleSearch(users) {
    let newUsers = []
    const str = searchQuery.toLowerCase()

    users.forEach(function(user) {
      if(user.name.toLowerCase().includes(str) || user.cellPhone.toLowerCase().includes(str)) newUsers.push(user);
    })

    return newUsers.sort(compare);
  }

 useEffect(() => {
    console.log("list")
    !dat.loading && search.current.focus();
  });

  let dat = {};

  dat = useQuery(CURRENT_USER);

  !(dat.loading || dat.error || !dat.data.me.admin) && auth.setAdmin();
  !(dat.loading || dat.error) && auth.setId(dat.data.me.id)

   dat = useQuery(LIST_USERS);


  if (dat.loading) return <LoadingDots></LoadingDots>;
  if (dat.error){
    console.error(dat.error.message)
    return auth.signOut();
    }

    return (
      <React.Fragment>
        <CreateUser queryRefresh = {() => dat.refetch()}></CreateUser>
      <HeadWrap>
        <SearchBar onChange={handleSearchChange} placeholder=" Search by name or cell #..." ref={search}/>
      </HeadWrap>
      <UserCols>

        <UserHeader>
          <span>NAME</span>
          <span>EMAIL</span>
          <span>OFFICE #</span>
          <span>CELL #</span>
          <span>LOCATION</span>
          <button onClick={dat.refetch}>REFETCH</button>
        </UserHeader>
        {!dat.loading &&
          handleSearch(dat.data.users).map(user => (
            <UserRow key={user.id}>
              <span>{ user.name }</span>
              <span>{ user.email }</span>
              <span>{ user.officePhone }</span>
              <span>{ user.cellPhone }</span>
              <span>{ user.location }</span>
              <EditUser user = {user} queryRefresh = {() => dat.refetch()}></EditUser>
              </UserRow>
            ))}
        </UserCols>
        </React.Fragment>
      );  
    }
```

**Comment by bmullan91** [comment]
@Saintroi When you call `refetch` the previous data will still be there, so you can still render them + the loading indicator, that should provide a better user experience.

One question, what the reasoning behind this code:

```js
let dat = {};

dat = useQuery(CURRENT_USER);

!(dat.loading || dat.error || !dat.data.me.admin) && auth.setAdmin();
!(dat.loading || dat.error) && auth.setId(dat.data.me.id)

dat = useQuery(LIST_USERS);
```

How come you're reassigning the `let dat` instead of using two separate `const`'s?

**Comment by Saintroi** [comment]
@bmullan91 That's the idea, but my point is that the call to refetch is causing my component to reload, which didn't happen before swapping over to graphql-hooks. Is there something I need to do differently to prevent the reload?

Per your question, you'll notice I'm calling 2 queries there. I need loading and error for both of them, but didn't want to create 4 different constants, especially since I don't need the CURRENT_USER loading and error once I get to the LIST_USERS query.

Previously I had two Query components in the render section of my component here and because they were separated I could use the loading and error constants without it trying to re-assign.

If I could break out the query calls into functions I could achieve that same functionality, but you can't conditionally call hooks.

**Comment by skywickenden** [comment]
I realise this is a bit stale, but I came across this issue as well and thought I would  document what I did.

It is due to the entirety of the data in the query response being over written from the new query result rather than patching it.  This happens on line 35 - 38 of [useQuery](https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/src/useQuery.js)

          // don't call the updateData that has been passed into useQuery here
          // reset to the default behavior of returning the raw query result
          // this can be overridden in refetch options
          updateData: (_, data) => data,

Ideally there would an option to apply a diffing algorithm that deletes stale data from the original object and copies new data to it. 

Meanwhile it is possible to manually override the result to prevent this, but you need to write a custom updateData callback for when you call refetch. For example this will remove any rows from a Foo collection that have been deleted in a mutation:

    refetch({
      updateData: (previousData, data) => {
        let dataCount = 0;
        previousData.Foo.forEach((row, index) => {
          row.id !== data.Foo[dataCount].id
            ? delete previousData.Foo[index]
            : dataCount++;
        });
        return previousData;
      }
    });

**Comment by skywickenden** [comment]
I've worked out a more generic solution that seems to be working for me. Use with caution as it hasn't been extensively tested and it is mutating the original object so there may be issues I've not thought of.. It makes use of this [diff](https://github.com/flitbit/diff) module so you will need to install that.

    import { observableDiff, applyChange } from "deep-diff";

    ...

    refetch({
      updateData: (previousData, data) => {
        observableDiff(previousData, data, differnce => {
          applyChange(previousData, data, differnce);
        });
        return previousData;
      }
    });
