### ISSUE TITLE
onError doesn't do what it suggests

### ISSUE THREAD

**Issue by levrik** [nearform/graphql-hooks#337]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 3.6.0

### Description

I wanted to use `onError` to implement a JWT session refresh after a failed request and then retry the request. But now I had to find out that `onError` only gets called if error logging is enabled (which already is quite weird). Also I can't return another `Promise` from `onError` to actually still resolve the request.

### Suggested solution

I could propose a solution to that via a PR if you are fine.
Now I have to wrap `axios` in some `fetch`-like API like suggested at the end of the README.
Actually I don't want to ship `axios` since it adds additional size to my bundle, also I don't want every request go through another layer of abstraction like the suggested fetch-wrapper.

**Comment by bmullan91** [comment]
@levrik sorry for the delay; I agree `onError` isn't that useful for this. You can solve this by passing your own `fetch` implementation, something along these lines:

```js
function customFetch(url, options) {
  return fetch(url, options).catch(error => {
    if (error.message === 'expired jwt') {
      refreshJWT().then(() => {
        // retry...
        return fetch(url, options);
      })
    }

    // re-throw 
    throw error
  })
}

const client = new GraphQLClient({
  url: '/graphql',
  fetch: customFetch
})
```

**Comment by levrik** [comment]
@bmullan91 Awesome. Thanks!
