### ISSUE TITLE
Typescript: Variables are not typed in hook functions

### ISSUE THREAD

**Issue by brookback** [nearform/graphql-hooks#348]
### Description

Right now, the various hook functions provides sending a type for the data response:

```ts
const { data } = useQuery<MyData>(QUERY);
```

However, the variables are *not* strongly typed because `UseClientRequestOptions.variables` is just an `object`:

```ts
interface UseClientRequestOptions {
  // ...
  variables?: object
  // ...
}
```

### Suggested implementation

I'm happy to provide a PR for this. I'd make sure to:

1. Type `UseClientRequestOptions` with a generic type:

   ```ts
   interface UseClientRequestOptions<Variables> {
     variables?: Variables
   }

   interface UseQueryOptions<Variables> extends UseClientRequestOptions<Variables> {
     ssr?: boolean
   }
   ```
2. Then use the new type in the various hooks, like `useQuery`:

   ```ts
   export function useQuery<ResponseData = any, Variables = object>(
     query: string,
     options?: UseQueryOptions<Variables>
   ): UseQueryResult<ResponseData, Variables>
```

**Comment by bmullan91** [comment]
@brookback Yep makes sense - PR welcomed :)
