### ISSUE TITLE
Adjusting variables passed to useQuery doesn't trigger request

### ISSUE THREAD

**Issue by Joezo** [nearform/graphql-hooks#35]
Whilst building the example next.js app i've run into a problem with the `useQuery` hook not triggering a request after the initial one. Even if the variables passed to it differ. 

Initial investigation suggests this if statement is unnecessary and causing the issue. https://github.com/nearform/graphql-hooks/blob/master/src/useQuery.js#L28

Hoping to get a failing test in place soon for this.

**Comment by jackdclark** [comment]
I've added failing tests for this in #36

**Comment by Joezo** [comment]
Cool, nice one. We should be able to close this and open an issue for the outstanding issue with `useClientRequest` returning data for different query/vars. Does that summarise that issue @jackdclark / @bmullan91 ?

**Comment by jackdclark** [comment]
Sounds good @Joezo, are you okay to raise the separate issue?

#36 Will close this once merged

**Comment by Joezo** [comment]
I've raised that here https://github.com/nearform/graphql-hooks/issues/37
