### ISSUE TITLE
Release Management and Code Versioning Documentation

### ISSUE THREAD

**Issue by galmail** [nearform/graphql-hooks#355]
### Package

This applies in general to all packages

- [x] `graphql-hooks`
- [x] `graphql-hooks-ssr`
- [x] `graphql-hooks-memcache`

### Description

We are looking to include in the documentation a chapter about how we are managing releases and code versioning.

**Comment by Joezo** [comment]
These are the existing docs on this https://github.com/nearform/graphql-hooks/blob/master/CONTRIBUTING.md#release-process - they're very vague.

**Comment by galmail** [comment]
Closing this as there is some doc already in the readme
