### ISSUE TITLE
Build breaks due to wrong way to cache package.json file(s) contents

### ISSUE THREAD

**Issue by simoneb** [nearform/graphql-hooks#357]
### Package

Whole monorepo

### Description

This has been addressed in #354 but depending on how quickly we can merge that it may make sense to pull that out as a standalone fix, so that other PR branches have their builds fixed.

**Comment by Joezo** [comment]
I'm planning on reviewing that PR in a couple of hours, so i don't think pulling it out will be worth it.

**Comment by simoneb** [comment]
sure just put this out there because it's blocking all other work due to the broken builds
