### ISSUE TITLE
Comparison: Apollo hooks

### ISSUE THREAD

**Issue by bkniffler** [nearform/graphql-hooks#363]
I've just discovered graphql-hooks and I'd love to know what the core differences are to apollo, and I guess its more people will wonder when discovering this library. Since apollo now also supports hooks API, and since there is a 1:1 migration guide from apollo to graphql-hooks, it looks like the differences are under the hood (performance, complexity, library size).

Would love to see a small part of docs dedicated to that subject!

Keep it up :)

**Comment by bmullan91** [comment]
@bkniffler Sorry for the lack of response on this - You rightly pointed out the key differences performance, complexity, library size.

Complexity and library size I think are reflected in the docs but not as a direct 1:1 comparison.
Performance is a grey area, we'd need to create a sample app and metrics to measure to accurately gauge performance. I don't have the time do such a task atm, but I'll leave this open for discussion/others to pick up.
