### ISSUE TITLE
tiny_lru__WEBPACK_IMPORTED_MODULE_0___default

### ISSUE THREAD

**Issue by and3rsonsousa** [nearform/graphql-hooks#366]
### Package

`graphql-hooks`
`graphql-hooks-ssr`
`graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: 3.2.1
- `graphql-hooks-ssr` version: 1.0.1
- `graphql-hooks-memcache` version: 1.0.4
- `react` version:  16.8.2
- Browser: Chrome 77.0.3865.90

### Description

Started to get this error one day ago only on localhost, on now(zeit) works properly. Downloaded Next.js example using graphql-hooks, no modification on the code 
and the same error has happened.
<img width="1038" alt="Captura de Tela 2019-09-24 às 01 31 35" src="https://user-images.githubusercontent.com/29865417/65481299-1c596b80-de6b-11e9-9a35-fd0953957dad.png">

**Comment by fabienheureux** [comment]
Exact same issue here 😶
