### ISSUE TITLE
SSR feature is broken since 3.6.1

### ISSUE THREAD

**Issue by terryyu** [nearform/graphql-hooks#371]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 3.6.1 or 4.0.0

### Description

SSR feature is broken since 3.6.1, you can test with the provided fastify-ssr example

### How to reproduce

Clone the project, go to examples/fastify-ssr, set graphql-hooks to different versions in package.json.

Set graphql-hooks to 3.6.1 or 4.0.0 in package.json
```
"graphql-hooks": "3.6.1",
```
Install, build and start the app, view page source.
```
<script type="text/javascript">
  window.__INITIAL_STATE__={};  
</script>
```
You can see the __INITIAL_STATE__ is empty. SSR is not working.

Now set graphql-hooks to 3.6.0 in package.json
```
"graphql-hooks": "3.6.0",
```
Install, build and start the app agian, view page source.
```
<script type="text/javascript">
  window.__INITIAL_STATE__={"bhilef":{"error":false,"data":{"users":[{"name":"Brian"},{"name":"Jack"},{"name":"Joe"}]}},"ej6ucw":{"error":false,"data":{"hello":"Hello Brian"}}};  
</script>
```
__INITIAL_STATE__ is not empty. SSR is working.

### Suggested solution (optional)
It seems to be related to this line
https://github.com/nearform/graphql-hooks/pull/298/files#diff-dd568ddecea113b2a4d3db093d410fa2R18
in the PR https://github.com/nearform/graphql-hooks/pull/298
the added condition of `!state.loading` is preventing SSR data fetching.

**Comment by bmullan91** [comment]
Fixed in `graphql-hooks@4.0.2`
