### ISSUE TITLE
Support for non-react frameworks

### ISSUE THREAD

**Issue by jdin** [nearform/graphql-hooks#386]
### Description

The project is tightly coupled with React, but there are more projects that support "hooks api".
For example [Haunted](https://github.com/matthewp/haunted). Would it be possible to make React dependency optional so that these hooks can also be used with other projects?

### Suggested implementation

Instead of directly importing react hooks you can make some kind of factory:

```javascript
export const createUseQuery = (useState, useEffect) => {
  // ...
};
```

Would do you think, guys? Would it be an option?

**Comment by bmullan91** [comment]
@jdin You can create an instance of the `GraphQLClient` and use it in any environment. We don't have any plans of decoupling the hooks from React though.
