### ISSUE TITLE
State not being updated after a second cache hit when updateData is set

### ISSUE THREAD

**Issue by bmullan91** [nearform/graphql-hooks#387]
### Package
`graphql-hooks`

### Environment

- `graphql-hooks` version: `4.0.1`

### Description

If the query has had a previous cache hit, then the variables change and the second request is also cached but it never updates the state due to:
1. `options.updateData` is set therefore we never reset the state (correct)
1. When useClientRequest finds a cache hit for the second query, it dispatches `CACHE_HIT` action, but it never updates because there is a check if the existing state is a cache hit which prevents unnecessary re-renders... see https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/src/useClientRequest.js#L24-L29

### How to reproduce

1. Pass an instance of `graphql-hooks-memcache` to `GraphQLClient({ cache: memCache() })`
1. Inside a component call `useQuery(query, { updateData: updateDataFn })`
1. Invoke the useQuery twice with separate variables (e.g. Infinite loading)
1. After the cache has been populated with the two queries, leave that page and revist to trigger the caching
1. The first query loads correctly and the data is rendered
1. When the second query is triggered, the state returned from `useQuery` remains the same.

### Suggested solution (optional)

Pass an additional action property `resetState` when dispatching `CACHE_HIT` which will do a check between the state.cacheKey vs the current cacheKey.

**Comment by bmullan91** [comment]
Fixed in `graphql-hooks@4.0.2`

**Comment by tadjohnston** [comment]
This seems to have produced a double render bug in this example: https://github.com/vercel/next.js/blob/master/examples/with-graphql-hooks/components/post-list.js

Not sure if I'm missing something, but `state.cacheKey` doesn't ever seem to exist.
