### ISSUE TITLE
Duplicated items when using pagination

### ISSUE THREAD

**Issue by joeynimu** [nearform/graphql-hooks#395]
### Package
- `graphql-hooks`

### Environment

- `graphql-hooks` version:^3.5.0
  
- `graphql-hooks-memcache` version: ^1.2.4
- `react` version: ^16.10.2
- Browser: chrome

### Description

I am using this package to consume a graphql API and my UI has a load more button which essentially loads more items if there is a `next_page`. But on fetching the next page I am getting duplicated items. This is evident for `React` complains that there are duplicated keys; I am using the `item_id` as the key.

I am not sure why this is the case. I expect it to get the next page of which I then merge the items on the `onUpdate` function. 

### How to reproduce
Have a look [this sandbox](https://codesandbox.io/s/snowy-resonance-npkm6)

**Comment by bmullan91** [comment]
@joeynimu Hey, sorry for the lack of response on this - did you ever get to the bottom of your issue? You're codesandbox link no longer works, so I can't take a look myself :(

**Comment by joeynimu** [comment]
Hey @bmullan91, I did! Turned out the issue was actually on my API. Thanks! 

One thing I noticed though, is that the `error` type should be an Object but it actually returns a Boolean. Not sure if it's a mismatch on the docs and API or it is something just happening to me

**Comment by bmullan91** [comment]
@joeynimu Ah 😅- I'll close this then.

RE the error object vs boolean, that changed in v4 (https://github.com/nearform/graphql-hooks/pull/354) what version are you running?
