### ISSUE TITLE
File upload from NodeJS

### ISSUE THREAD

**Issue by lynxtaa** [nearform/graphql-hooks#399]
### Package

- [x] `graphql-hooks`
- [x] `graphql-hooks-ssr`
- [ ] `graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: 4.0.2
  

### Description

Is there a way to use `client.request` to upload files from NodeJS?

**Comment by lynxtaa** [comment]
Ok, right now `graphql-hooks` is using [extract-files](https://github.com/jaydenseric/extract-files) which doesn't support Node Streams. Hopefully it will, after this PR https://github.com/jaydenseric/extract-files/pull/11

Then `graphql-hooks` can be updated to support file upload from NodeJS

**Comment by bmullan91** [comment]
Fixed in #422 - available in `graphql-hooks@4.3.0` 🚀
