### ISSUE TITLE
Consider using lerna

### ISSUE THREAD

**Issue by Joezo** [nearform/graphql-hooks#40]
It might be worth using `lerna` for this project. Given that we have this repo, `graphql-hooks-ssr` and `graphql-hooks-memcache` already. I expect that to grow in future so may be worth setting up a monorepo soon.

**Comment by simoneb** [comment]
My personal experiences with lerna are not very good. On the other hand I hear other people using it with success. The main troubles I've come across when using it is that it easily messes up packages, and in many cases something that would have usually required a single `npm i` in a nested package required instead various attempts of combinations of `npm i` or bootstrapping in the root folder then another `npm i` in the nested package, pretty much defeating any benefits of using lerna in the first place.

Aside from this, let's consider what benefits lerna would provide here, I think the main selling point is that you can reference packages from each other, do we need that?

**Comment by jackdclark** [comment]
Completed in #78
