### ISSUE TITLE
SSR pre-fetching is not working

### ISSUE THREAD

**Issue by zelphir** [nearform/graphql-hooks#439]
### Package

`graphql-hooks`
`graphql-hooks-ssr`
`graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: 4.3.0
  
- `graphql-hooks-ssr` version: 1.1.5
- `graphql-hooks-memcache` version: 1.3.0
- `react` version: 16.12.0
- Browser:

### Description
Using the example app from the `next.js` repo (straight from [here](https://github.com/zeit/next.js/tree/canary/examples/with-graphql-hooks), the only thing is I've updated `graphql-hooks` to latest version, but the issue happens also using version `3.6.1`) the pre-fetch server side doesn't work. This is because the `graphQLClient` is always a new one (https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/init-graphql.js#L17-L21) and the array with the `ssrPromises` gets lost, so no pre-fetch.

### How to reproduce

- `yarn create next-app --example with-graphql-hooks with-graphql-hooks-app`
- ` cd with-graphql-hooks-app`
- `yarn dev`

Obesrve that the posts are not loaded server side (you can see the loading message, the fetch happens client side)

**Comment by zelphir** [comment]
related to https://github.com/zeit/next.js/issues/9865

**Comment by bmullan91** [comment]
related to #434

**Comment by galmail** [comment]
I tried it, although not sure yet what will be the correct solution here, but I realised that if you upgrade  the packages `graphql-hooks, graphql-hooks-ssr, graphql-hooks-memcache` to the latest versions and then also update `useQuery` in `components/post-list.js` like so:

```javascript
const { loading, error, data, refetch } = useQuery(allPostsQuery, {
    variables: { skip, first: 10,
      updateData: (prevResult, result) => ({
        ...result,
        allPosts: [...prevResult.allPosts, ...result.allPosts],
      }),
    }
  })
```

And for the sake of testing SSR with useQuery, try to comment these lines in `lib/init-graphql.js`:

```javascript
if (typeof window === 'undefined') {
    return create(initialState)
}
```

**Comment by danwilliams** [comment]
This is now resolved by https://github.com/vercel/next.js/pull/13799 which has been merged.
