### ISSUE TITLE
Data variable from useQuery is briefly undefined – inconsistent with TS types

### ISSUE THREAD

**Issue by brookback** [nearform/graphql-hooks#444]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 4.3.0
- `react` version: 16.12.0
- Browser: Chrome

### Description

I noticed the `data` variable returned from `useQuery` is undefined when first rendering a component. This collides with the fact that the types say it's always defined.

See `index.d.ts`:

```ts
interface UseClientRequestResult<ResponseData> {
  loading: boolean
  cacheHit: boolean
  data: ResponseData // <- Here
  error?: APIError
}
```

### How to reproduce

```tsx
const { data, loading, error } = useQuery<
        QueryData,
        QueryVariables
    >(QUERY, {
        variables: {},
    });

console.log({ data, loading, error });
```

**Result**

<img width="484" alt="image" src="https://user-images.githubusercontent.com/30257156/72808371-b5519500-3c59-11ea-9fb0-0dd44e0ede18.png">

### Suggested solution

Make `data` optional/falsy on `UseClientRequestResult` if we can't guarantee it being truthy while loading:

```diff
interface UseClientRequestResult<ResponseData> {
  loading: boolean
  cacheHit: boolean
- data: ResponseData
+ data?: ResponseData
  error?: APIError
}
```

**Comment by brookback** [comment]
Note that fixing this is a breaking change, since if people rely on `data` always being defined, making it optional will cause a bunch of compile errors.

**Comment by jh3y** [comment]
Where should we go with this one?

Seems like the `Suggested solution` is one we should merge in 👍 

However, we don't have a `CHANGELOG`? or release notes? To communicate a breaking change like this.

**Comment by brookback** [comment]
@jh3y There is a changelog in https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/CHANGELOG.md.

However, if this repo is following semantic versioning (which I think it is), the major version must be bumped from `5.x.x`.

**Comment by jh3y** [comment]
Sorry, my bad, I did see that after writing this 🤦 
I'd initially looked at release notes and must've missed it 😅 

Yeah, a major bump sounds like the right way forward here 👍 Thanks!
