### ISSUE TITLE
Please upgrade sindresorhus/fnv1a for IE11 compatibility

### ISSUE THREAD

**Issue by chughes87** [nearform/graphql-hooks#476]
### Package

`graphql-hooks-memcache`

### Environment

- `graphql-hooks-memcache` version: 1.3.1

- Browser: IE11

### Description

Syntax error in IE11 when using the current version of sindresorhus/fnv1a

### How to reproduce

Load a page in IE11 that utilizes this library

### Suggested solution (optional)

Upgrade sindresorhus/fnv1a to 2.0.0

**Comment by chughes87** [comment]
@all-contributors please add chughes87 for contributions

**Comment by chughes87** [comment]
@all-contributors please add chughes87 for Code

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by bmullan91** [comment]
@chughes87 Can you provide a codesandbox as an example. I've already looked into this (and resolved it) in https://github.com/nearform/graphql-hooks/pull/445.

**Comment by chughes87** [comment]
I'd like to put a PR up. see https://github.com/nearform/graphql-hooks/pull/477

**Comment by bmullan91** [comment]
@chughes87 got for it! The process is to open the contribution PR after the actual contribution 😄

**Comment by thomheymann** [comment]
I can't reproduce this. The cra example in the repo which uses `graphql-hooks-memcache` package works fine in IE11: https://graphql-hooks-cra.netlify.com/

What is the exact syntax error you're getting?
Are you transpiling your app using babel for IE11 support? It's expected that modern syntax will not work in older browsers without transpiling code down to ES5

**Comment by chughes87** [comment]
I've started transpiling select module imports for IE support. I guess it's a big ask for all modules to be es5 compatible.
