### ISSUE TITLE
Consider using semantic-release

### ISSUE THREAD

**Issue by bmullan91** [nearform/graphql-hooks#48]
## Notes
- commits will need to follow a certain format `fix`, `feat` or `BREAKING CHANGE`
- semantic-release figures out what the new version should be
- generates release notes
- generates git tag
- publish the new release

see https://github.com/semantic-release/semantic-release for more info.

**Comment by jackdclark** [comment]
@bmullan91 I've been investigating this one this morning.

Lerna supports the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#specification) via config or a [`--conventional-commits` flag](https://github.com/lerna/lerna/blob/030de9d6285f2b364ed1460b9534bc2190acdf7a/commands/version/README.md#--conventional-commits). When run with this flag, lerna version will use the spec to determine the version bump and generate CHANGELOG.md files.

Lerna also has a [`--github-release` flag](https://github.com/lerna/lerna/blob/030de9d6285f2b364ed1460b9534bc2190acdf7a/commands/version/README.md#--github-release) - which, when used with `--conventional-commits`,  will create an official GitHub release based on the changed packages.

As we already follow a squash based workflow on this project when merging PRs, it wouldn't be much overhead to enforce us as maintainers to use conventional commits when merging PRs & we'll then get all of the above. It also means we wouldn't have to force contributors to follow the spec when raising PRs, which could be off-putting if we enforce too much process. (See [Do all my contributors need to use the conventional commit specification?](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#do-all-my-contributors-need-to-use-the-conventional-commit-specification))

Thoughts @bmullan91 @Joezo?
