### ISSUE TITLE
Different updateData behaviour depending on variables

### ISSUE THREAD

**Issue by brookback** [nearform/graphql-hooks#489]
### Description

We've got a traditional "infinite loading" pagination as described in the README, with a custom `updateData` function which appends new recordings as they come in. Everything is controlled with a `skipCount` state hook variable.

That works great, but when we're manipulating other *other* variables, such as a filter, the same `updateData` will be used and causes incorrect behaviour, since it'll just append new data for infinite loading.

Below, I *don't* need the `updateData` function for when `slug` and `filter` variables change, but only for `skipCount`.

```tsx
// Query for getting a certain team's posts
const MY_QUERY = /* GraphQL */ `
  query MyQuery(
    $skipCount: Int!
    $slug: ID!
    $someFilter: String
  ) {
  teamBySlug(slug: $slug) {
    name
    posts(filter: $someFilter, skip: $skipCount, limit: 10) {
      name
    }
  }
}`;

const MyComponent = (props) => {
  const [skipCount, setSkipCount] = React.useState(0);
  const [filter, setFilter] = React.useState('');

  const res = useQuery(MY_QUERY, {
    updateData,
    variables: {
      skipCount,      // <- Should infinite load
      slug: props.slug,      // <- Should not
      someFilter: filter,      // <- Should not
    }
  });
}

// Infinite loading of posts
const updateData = (prevData, data) => {
  return {
    ...data,
    teamBySlug: {
      ...data.teamBySlug,
      posts: [...prevData.teamBySlug.posts, ...data.teamBySlug.posts]
    }
  }
}
```

#### Questions

- Is `useManualQuery` with a conditional paginating `updateData` function depending on which variables that change the way to go?
- Using *two* `useQuery` calls: one with `updateData`, one without? And cleverly merge their results somehow.

### Suggested implementation

One thing could be to pass the variables on to the `updateData` function in order let it decide which data to use. Downer to mess up the nice function signature though.

***

Thanks for input! I realised this became more of a question rather than a feature request 😄 Mea culpa.

**Comment by bmullan91** [comment]
@brookback stupid question: have you tried conditionally passing in the `updateData`? If so how does that break things? 😆 

```js
const res = useQuery(MY_QUERY, {
    updateData: skipCount ? updateData : undefined,
    variables: {
      skipCount,      // <- Should infinite load
      slug: props.slug,      // <- Should not
      someFilter: filter,      // <- Should not
    }
  });
}
```

**Comment by brookback** [comment]
@bmullan91 Not stupid, haha :) It'll work when `skipCount` is zero, but as soon as I load more items (`skipCount > 0`), that `updateData` function will be used also for subsequent changes to `someFilter`.

It breaks by React complaining about identical keys:

```
Warning: Encountered two children with the same key, `d7yEv6vFpkCDZ4kye`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

**Comment by brookback** [comment]
I introduced some arbitrary rules in my listing to circumvent bugs here:

1. Setting filter and skip count is done in a single `setState`.
2. Switching filters automatically sets `skipCount` to zero.
3. Setting skip count doesn't affect filters.
4. Setting skip will use a paginated `updateData`.

2) effectively "resets" everything, which is an okay tradeoff.

```tsx
const [configVars, setConfigVars] = React.useState({
  skipCount: 0,
  filter: false,
});

const res = useQuery<QueryData>(PROJECTS_QUERY, {
        variables,
        updateData: configVars.skipCount ? updateData : undefined,
});

// Toggle filters
<FiltersToggle onChange={(val) => setConfigVars({
  skipCount: 0, // Resets pagination
  filter: val,
})} />

// Load more
setConfigVars(prev => ({
  ...prev,
  skipCount: projects.length,
}))
```

***

So. The core issue has a workaround. Even if `updateData`'s function signature would be amended (with `variables`) I don't think it'd be a non-trivial fix for the app.

**Comment by admataz** [comment]
hi @brookback  - just reviewing this issue - is this working satisfactorily for you now?  I'm not sure there's a better/ more elegant solution this library can provide to your workaround at this point

**Comment by brookback** [comment]
@admataz This is okay! I did the workaround described above. Thanks!
