### ISSUE TITLE
Typo in GraphQLClient typo in index.d.ts?

### ISSUE THREAD

**Issue by debugpai** [nearform/graphql-hooks#491]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 4.4.4
- `react` version: N/A
- Browser: n/a

### Description
In [this line](https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/index.d.ts#L177) the type for `client` is defined as `GraphqlClient` which is not available in the file. There is however a `GraphQLClient`. Does this need to be changed? I can make this changed if its the right one.

### Suggested solution (optional)
Change `GraphqlClient` to `GraphQLClient`

**Comment by bmullan91** [comment]
@debugpai looks like it, PRs welcome :)

**Comment by jh3y** [comment]
Were you able to put together this change @debugpai? Else, I can self-assign and make the change 👍

**Comment by debugpai** [comment]
Hey sorry I didn't pick this up yet. I will work on it this week

**Comment by jh3y** [comment]
No problem 👍 I've assigned you so people know.
