### ISSUE TITLE
Cache not working?

### ISSUE THREAD

**Issue by heymartinadams** [nearform/graphql-hooks#492]
### Environment

`graphql-hooks@4.4.4`
`graphql-hooks-memcache@1.3.2`
`preact@10.4.0` (not react). ← could this be the reason?
Browser: Chrome 81.0

### Description

For some reason, cache isn’t working.

#### index.js

```jsx
import { GraphQLClient, ClientContext } from 'graphql-hooks'
import memCache from 'graphql-hooks-memcache'
...
const client = new GraphQLClient({
	headers: {
		...(apiToken && { authorization: `Bearer ${apiToken}` }),
	},
	url: '../api',
	cache: memCache(),
})
<ClientContext.Provider value={client}>
	<App />
</ClientContext.Provider>
```

#### App.js

```jsx
import { useQuery } from 'graphql-hooks'
import apiEvents from '%/queries/Event/events'

// ...columns, filter are set here...

const variables = {
	first: columns,
	orderBy: { dateStart: 'asc' },
	where: filter,
}
const { loading, data, error, cacheHit } = useQuery(apiEvents, { variables })

console.log(cacheHit)
```

`cacheHit` remains `false` even if the user resets all variables to their default state. For example, on load, filter is `{}`. User checks “find dance events” option, and filter becomes `{ AND:[{ eventTopics: { some: { name: { equals: "dance" } } } }] }`. Then user unchecks option and filter reverts to `{}`. In each instance, however, `cacheHit` remains `false` and query is sent anew to server (with corresponding delays).

#### events.js
```js
import EventFragment from '%/fragments/Event'

export default `
	query(
		$first: Int
		$orderBy: EventOrderByInput
		$where: EventWhereInput
	) {
		events(
			first: $first
			orderBy: $orderBy
			where: $where
		) {
			...EventFragment
		}
	}
	${EventFragment}
`
```

**Comment by bmullan91** [comment]
@heymartinadams Do not rely on `cacheHit` see https://github.com/nearform/graphql-hooks/issues/428 check if the actual network request is made.

If you're still seeing this issue could you create a codesandbox - there's a good chance has something todo with preact !== react 😅

**Comment by heymartinadams** [comment]
Sounds good. Thanks 🙏
