### ISSUE TITLE
Ability to reset the data after useMutation

### ISSUE THREAD

**Issue by yanickrochon** [nearform/graphql-hooks#494]
### Description

When `useMutation` returns data, there should be a way to clear that data away as if no calls have been made, that is return the state of the hook to the one it was before invoking the mutation function.

### Suggested implementation

```js
const [ updateFoo, { loading, data, error, reset } = useMutation(FOO_MUTATION);
```

Calling `reset` would clear `data` and `error` and cancel any ongoing request.

**Comment by mcollina** [comment]
would you like to send aPR?

**Comment by jh3y** [comment]
Have you begun working on a solution for this @yanickrochon?
Can we assign this to you? 👍

**Comment by yanickrochon** [comment]
@jh3y  Because of time constraint, I have switched to Apollo server and client for this project. I'm already way behind on schedule and I'm unable to allocate on more at the moment. I have taken the time to look at the code and believe that simply wrapping a function with a reset state (the feature is already there) to revert using the previous context would be a good starting point, but this would need to be tested and this is the part which I have no time for. Not right now anyway.

**Comment by jh3y** [comment]
Completely understandable @yanickrochon 🙂 
Thanks for the prompt response!
