### ISSUE TITLE
graphql-hooks-memcache@1.3.2 causes a runtime SyntaxError in Safari

### ISSUE THREAD

**Issue by InsaneViku** [nearform/graphql-hooks#496]
### Package

`graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: 4.4.4
- `graphql-hooks-memcache` version: 1.3.2
- Browser: Safari

### Description

When loading a site with a js bundle that includes `graphql-hooks-memcache@1.3.2` in Safari, I encounter the following runtime error as the browser parses/evaluates the bundle:

`SyntaxError: No identifiers allowed directly after numeric literal`

The error points to the following in my bundle (dev bundle version):

<img width="1343" alt="Screen Shot 2020-04-28 at 2 54 42 PM" src="https://user-images.githubusercontent.com/7233174/80541607-45d9f880-8960-11ea-9baa-3df57235e27f.png">

This points to the `graphql-hooks-memcache@1.3.2` update which includes [`@sindresorhus/fnv1a@2.0.0`](https://github.com/sindresorhus/fnv1a/releases/tag/v2.0.0). This version of the package now utilizes BigInt. Since Safari doesn't support BigInt at the time of writing (https://caniuse.com/#feat=bigint, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Browser_compatibility), we get this issue.

### How to reproduce

Have a look at this Codesandbox in Safari: https://codesandbox.io/s/unruffled-brook-cb8b6 - the error will show up in the browser emulator, like below:

<img width="1680" alt="Screen Shot 2020-04-28 at 3 37 42 PM" src="https://user-images.githubusercontent.com/7233174/80544600-3cec2580-8966-11ea-8dd4-75a9dc2e9606.png">

Compare this with using `graphql-hooks-memcache@1.3.1`: https://codesandbox.io/s/infallible-cloud-oh7w4

### Suggested solution (optional)

Not sure how to solve this right now - at the very least, I wanted to report it. This prevents usage on Safari, and AFAIK, the community should be able to use `graphql-hooks-memcache` on browsers as per https://github.com/nearform/graphql-hooks#support, which currently includes Safari (as well as iOS Safari).

If I think of any solutions, I'll update accordingly.

**Comment by InsaneViku** [comment]
A **workaround** that I used for my current project was to downgrade `graphql-hooks-memcache` to `1.3.1`, so the state of the project is not impacted. Looking at https://github.com/nearform/graphql-hooks/commits/master/packages/graphql-hooks-memcache, considering that `1.3.2` was released with just the `@sindresorhus/fnv1a` major version bump to `2.0.0`, there is no loss of added functionality, features, or fixes by downgrading to `1.3.1` in the interim.

A concern I'd like to raise is the rationalization behind the `1.3.2` bump, as well as the semver chosen:

- `1.3.2.` was released for https://github.com/nearform/graphql-hooks/pull/480, which doesn't seem proper - IE11 also doesn't support BigInt. It sounds like this may have been a miss that will need to be addressed now.
- the patch version bump from `1.3.1` to `1.3.2` doesn't seem right as well. Even though the **API** for `@sindresorhus/fnv1a@2.0.0` remains backwards compatible for projects that used `@sindresorhus/fnv1a@1.2.0`, it's a still major bump due to BigInt usage. It looks like the major version bump for `@sindresorhus/fnv1a` was due to requiring `node > 10`, which brings up another point - was `@sindresorhus/fnv1a` intended to only be used in `nodejs` and not in the browser? This is just my thought given the `node` requirement for that package, but there's no clear verbiage on that repo to state as such.

**Comment by miliu99** [comment]
Ok, I ran into this problem for a while and today I took time to find the root cause, and it pinpoints to this package, so I found this post. 

It it strange that I initially had this problem with version ^1.3.1, then upgraded to the latest version 1.3.2 in hoping it fixes it, but it didn't. After seeing this post, however, I downgraded to ^1.3.1 and it works -- really weird.

Another interesting fact is that if this problem occurs, Safari doesn't work both on my iPhone and on my MacBook. However, Chrome works fine on my MacBook (v13.1), but not on my iPhone X (v13.4.1).

Also, it throws this error just by including this package, it doesn't matter if you use it or not.

**Comment by InsaneViku** [comment]
@mcollina, @bmullan91, and other maintainers - were you able to look at this issue? It's an important browser support related issue, as it breaks Safari and IE. Per https://github.com/nearform/graphql-hooks#support, both should be supported at this time.

**Comment by movila** [comment]
the owner of [@sindresorhus/fnv1a](https://github.com/sindresorhus/fnv1a) points out [that](https://github.com/sindresorhus/fnv1a/issues/10) 

> uses BigInt literals, which ... iOS Safari doesn't support.

**Comment by InsaneViku** [comment]
Thank you @galmail, fix looks great!
