### ISSUE TITLE
Data in useQuery is undefined on first render

### ISSUE THREAD

**Issue by vladshcherbin** [nearform/graphql-hooks#517]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 4.4.4
- `react` version: 16.13.1
- Browser: chrome

### Description

Data is `undefined` until it's fetched. Docs say it should be an object. While it's `undefined` it's not possible to use this:

```js
const { loading, error, data: { users } } = useQuery(usersQuery)
```

Using this syntax is convenient when you need to later use variable (users) multiple times - check length, map over it, etc.

### How to reproduce

I believe there is no need to reproduce.

### Suggested solution (optional)

Maybe it should be an object always like it's written in the docs? It'll also make an example above work 🤔 

Related typings issue - https://github.com/nearform/graphql-hooks/issues/444

**Comment by ovhemert** [comment]
The `data` can be `undefined` on first render. This has been adjusted in the types. See #567 
Returning it as an object would cause side effects.
