### ISSUE TITLE
String variable in useMutation is converted to int

### ISSUE THREAD

**Issue by vladshcherbin** [nearform/graphql-hooks#522]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 4.4.4
- `react` version: 16.13.1
- Browser: chrome

### Description

When I use variables in `useQuery` and `useMutation`, they behave differently. Here is schema I have:

```gql
type Permission {
  id: Int!
  title: String!
}

input UpdatePermissionInput {
  id: Int!
  title: String
}

extend type Query {
  permission(id: Int!): Permission
}

extend type Mutation {
  updatePermission(input: UpdatePermissionInput!): Permission!
}
```

**useQuery**: when I perform `permission` query and use string as `id` variable, a wrong type error is received:

```js
const permissionQuery = `
  query permission($id: Int!) {
    permission(id: $id) {
      id
    }
  }
`

useQuery(permissionQuery, { variables: { id: '9' } })
```

**useMutation**: when I perform `updatePermission` mutation and use string as `id` variable, it's automatically converted to int and no error is received:

```js
const updatePermissionMutation = `
  mutation updatePermission($input: UpdatePermissionInput!) {
    updatePermission(input: $input) {
      id
    }
  }
`

const [updatePermission] = useMutation(updatePermissionMutation)

updatePermission({ variables: { input: { id: '9', ...values } } })
```

Request:

![image](https://user-images.githubusercontent.com/6711845/83705345-59424880-a61d-11ea-82ae-c3a61b34cbc9.png)

### How to reproduce

Use string variable in mutation which expects int type.

### Suggested solution (optional)

Passing wrong variable type should also throw error in mutation 🤔

**Comment by salmanm** [comment]
I couldn't reproduce it @vladshcherbin. Here's a quick [codesandbox](https://codesandbox.io/s/modest-gagarin-p3n85?file=/src/App.js).

![image](https://user-images.githubusercontent.com/2510597/97858907-d89b8b80-1d25-11eb-8bc4-62b44aa2e74c.png)

the `id` stays as string `'2'`. If you can post any reproducible link, that'll be helpful.
