### ISSUE TITLE
TypeError: Cannot read property 'useGETForQueries' of undefined

### ISSUE THREAD

**Issue by medev21** [nearform/graphql-hooks#547]
I'm using graphQL hooks for my project, I'm running into an issue with testing, it renders this error:

`TypeError: Cannot read property 'useGETForQueries' of undefined`

It fails in this line of code that belongs to a search component:

`const [searchManual, { loading: searchLoading, data, error }] = useManualQuery(SEARCH_QUERY);`

By default useGETForQuereies is false, but not sure why this error comes up when running the test. The project runs ok, it's just the test case. I have explicitly added the boolean for that variable in the GraphQlClient

graphql interceptor JS file

```
const gqlAxios = axios.create()
gqlAxios.interceptors.response.use(
  function (response) {
    if(response.status === 401 || response.status === 403 )
        window.location.href = config.api.LOGIN_URL;
    
    return response;
  },
  function (error) {
    console.log("responseError", error);
    return Promise.reject(error);
  }
)
gqlAxios.interceptors.request.use(
  function (config) {
    config = {
      ...config,
      headers: {
          ...config.headers,
          'session': getCookieValue()
      }
    }
    return config;
  }
)


const fixed = config.api.APP_GQL_HOST;
const url = fixed + 'graphql';

export const client = new GraphQLClient({ url, fetch: buildAxiosFetch(gqlAxios), useGETForQueries: false });
```

the client constant will be exported to index.js and used as a value in the ClientContext.Provider.

```
const Wrapped = (
  <ClientContext.Provider value={client}>
    <App />
  </ClientContext.Provider>
)

ReactDOM.render(
  Wrapped, document.getElementById('root')
);
```
Could this be an error from jsdom, this is the actual console error from running a test:

```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [TypeError: Cannot read property 'useGETForQueries' of undefined]
```
If so, how can this be resolved? I'm just trying to solve pass a simple test case:

```
it('Expect component in the document', () => {

        const { getByTestId } = render(<Search />);
        const component = getByTestId("test");
        expect(component).toBeInTheDocument();

    });
```
Is there an extra configuration I need to be adding? I would like to use msw , mock service worker, but I'm stuck with this error and can not move forward. Has anyone experience this error with graphql hooks? I appreciate your insights with this issue.

**Comment by rasovica** [comment]
We are running in the same problem. It also occurs only during tests. But sadly I am not sure what the proper solution is

**Comment by mcollina** [comment]
We are currently quite busy. If you send a PR we'll be happy to review, otherwise it would have to wait for a bit.

**Comment by vitorboccio** [comment]
Any update on this one ?

**Comment by mcollina** [comment]
@ovhemert could you take a look?

**Comment by ovhemert** [comment]
The `undefined` in the error message `TypeError: Cannot read property 'useGETForQueries' of undefined` refers to the client object. When calling the `useQuery` function you can pass in the client object using the options like this:

```js
useQuery(query, { client })
```

If no client is passed into this function, the component relies on the `ClientContext` it is wrapped in:

```js
<ClientContext.Provider value={client}>
```

It could be, that the component that you are testing, is originally wrapped inside the `ClientContext` when used in your application. But when testing the individual component, this context could be missing.

Here is an example to illustrate the different outcomes in a test:

```js
const Component3 = () => {
  useQuery(query, { client })
  return <div>hello</div>
}

const Component2 = () => {
  useQuery(query, {})
  return <div>hello</div>
}

const Component1 = () => {
  return (
    <ClientContext.Provider value={client}>
      <Component2 />
    </ClientContext.Provider>
  )
}

render(<Component1 />) // just fine, Component2 uses client from ClientContext
render(<Component2 />) // TypeError: Cannot read property 'useGETForQueries' of undefined (there is no client object available)
render(<Component3 />) // just fine, Component3 is like Component2. Only now we manually pass in the client object
````

So, if I compare this to your test example... 
```js
const { getByTestId } = render(<Search />);
const component = getByTestId("test");
expect(component).toBeInTheDocument();
```
... your `<Search />` is like `<Component2/>`. If you want to test it individually, you can wrap it in a `ClientContext`.

Let me know it that works for you.

**Comment by medev21** [comment]
Ah I see,I have added the context and it works. Thanks for the detailed clarification!
