### ISSUE TITLE
Can you call multiple mutations in one component?

### ISSUE THREAD

**Issue by miliu99** [nearform/graphql-hooks#548]
It appears that it messes up if I call two mutations in one component and I'm not quite sure if I did something wrong or if it's not supported. I searched around and found that there is a compose utility in apollo-client. Do I have to use something similar with graphql-hooks?

**Comment by salmanm** [comment]
If I understand the issue correctly, you're trying to call two mutations in one request. So something like

```
  mutation AddProduct($name1: String, $name2: String) {
    add1: addProduct(name: $name1) {
      id
      name
    }

    add2: addProduct(name: $name2) {
      id
      name
    }
  }
```

I just tried it and found it to be working fine. This is the response I get.

```js
{
  "data": {
    "add1": {
      "id": "5",
      "name": "P1"
    },
    "add2": {
      "id": "6",
      "name": "P2"
    }
  }
}
```

If you meant something else @miliu99, please post a code snippet and describe the problem in detail.
