### ISSUE TITLE
Usage with graphql-ws

### ISSUE THREAD

**Issue by evenfrost** [nearform/graphql-hooks#605]
### Description

Would be great if the library could be used with [`graphql-ws`](https://github.com/enisdenjo/graphql-ws), which is GraphQL over WebSocket implementation.

### Suggested implementation

Current `GraphQLClient` implementation uses fetch, which requires `url` param to be HTTP(S) requests. A possible implementation is the ability to use ws(s) protocol here as well.

**Comment by mcollina** [comment]
This sounds great! Would you like to send a Pull Request to address this issue?
