### ISSUE TITLE
[memcache] Buffer is not defined (in browser)

### ISSUE THREAD

**Issue by samkelleher** [nearform/graphql-hooks#608]
### Package

`graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: 5.0.0
- `graphql-hooks-memcache` 2.0.0
- `react`: 16.13.1
- `Browser`: Chrome 88

### Description

```
ReferenceError: Buffer is not defined
fnv1a
.my-project/node_modules/graphql-hooks-memcache/es/graphql-hooks-memcache.js:101
   98 | }
   99 | 
  100 | function fnv1a(input) {
> 101 |   if (input instanceof Buffer) {
  102 |     return fnv1aBuffer(input);
  103 |   } else if (typeof input === 'string') {
  104 |     return fnv1aString(input);
```

### How to reproduce

Simply having the memcache library in the page causes the error. I didn't see any note that the library is Node only, is it?

```jsx
import { GraphQLClient } from "graphql-hooks";
import memCache from "graphql-hooks-memcache";

const client = new GraphQLClient({
  url: "/graphql",
  cache: memCache(),
});
```

**Comment by simoneb** [comment]
@samkelleher Have you tried using a polyfill for Buffer?

**Comment by mcollina** [comment]
Are you using Webpack 5? @simoneb I think we should do a spike on how to use with Webpack 5.

**Comment by simoneb** [comment]
@mcollina good point, webpack5 apparently doesn't polyfill some Node globals automatically anymore, therefore the fnv1a lib we're using won't work unless Buffer is polyfilled manually or we use a different approach altogether.

**Comment by samkelleher** [comment]
I see yes indeed I am using Webpack 5.

To resolve this, I installed "buffer", and then in the browser webpack config added

```
new webpack.ProvidePlugin({ Buffer: ["buffer", "Buffer"] })
```

to the configs `plugins`, which adds the pollyfill. Once I did this, memcache worked normally.

I'll leave this ticket open as I think it would be helpful to either auto-bundle a Buffer pollyfill (if needed) in a browser build (if you make one), or at least, add a line or two in the installation + setup notes for memcache so say that Buffer needs pollyfilling, as yeh it's not obvious straight away that it's a webpack thing.

**Comment by simoneb** [comment]
Thanks for the update. To be clear, it's a webpack 5 change which presumably broke many projects, you can find it in the migration guide.

**Comment by mcollina** [comment]
I think we could migrate from Buffer to TypedArrays here, there is no real need to use buffer.

**Comment by simoneb** [comment]
Buffer is used in fnv1a, which is https://github.com/sindresorhus/fnv1a. Not sure why we imported the code in this repo though

**Comment by mcollina** [comment]
It's forked to add some different feature. We can just remove Buffer completely
