### ISSUE TITLE
Support for micro-frontend architecture with create-shared-react-context

### ISSUE THREAD

**Issue by jgolden17** [nearform/graphql-hooks#610]
### Description

When using `graphql-hooks` in a micro-frontend application, developers have to provide the `ClientContext` to all [child modules](https://github.com/americanexpress/one-app/blob/main/docs/api/README.md) that use this package.  Using [create-shared-react-context](https://github.com/americanexpress/create-shared-react-context) to [create the ClientContext](https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/src/ClientContext.js#L3) would allow applications to provide the client context to all child modules from with in the application's root module.

### Suggested implementation

Replace
```js
import React from 'react'

const ClientContext = React.createContext()

ClientContext.displayName = 'ClientContext'

export default ClientContext
```
with 
```js
import createSharedReactContext from 'create-shared-react-context';

const ClientContext = createSharedReactContext({}, 'graphqlHooks');

ClientContext.displayName = 'ClientContext'

export default ClientContext
```

**Comment by simoneb** [comment]
I don't see much value in introducing a dependency on a module which is no more than 10 lines of code and which could easily be implemented at the application level if you need use this library in such a scenario. Besides, that approach is not even the universally right way to build micro frontends. Why should this library force users to rely on a memoized context in the first place? That's just one of many ways to structure a micro frontend application.
