### ISSUE TITLE
New release of graphql-hooks-memcache

### ISSUE THREAD

**Issue by stefanoruth** [nearform/graphql-hooks#611]
Hi thanks for this set of packages, we really like it and use it on multiple projects 😄 

If posible would you be so kind to make a new release of `graphql-hooks-memcache`

Its because of this latest pr merged which fixes the buffer issue https://github.com/nearform/graphql-hooks/pull/609 with webpack 5, this would make us able to remove the hacks we have to make this work.

**Comment by simoneb** [comment]
released graphql-hooks-memcache 2.1.0
