### ISSUE TITLE
Local set up included in contributing guidelines/getting started

### ISSUE THREAD

**Issue by jh3y** [nearform/graphql-hooks#69]
### Description
For a fresh contributor there are no guidelines on how to set up the project in order to develop against it. This may be related to #40. 

On a fresh clone, being able to jump straight into development would be ideal 👍 

### Suggested implementation
Extra information included in the `CONTRIBUTING.md` file either pointing at starter apps or with instructions on how to set up as a monorepo?

**Comment by jackdclark** [comment]
This would be great. @Joezo is currently working on #12 to add an example app to the next.js repo, but we could create some examples within this repo too. We're looking into #40 now so will look into adding an examples folder with a basic app in there.
