### ISSUE TITLE
New community link

### ISSUE THREAD

**Issue by Eomm** [nearform/graphql-hooks#719]
### Description

Spectrum is read-only now

https://spectrum.chat/spectrum/general/join-us-on-our-new-journey~e4ca0386-f15c-4ba8-8184-21cf5fa39cf5

We should drop it because it is the first badge after the title.
I think we could turn on GitHub discussions as a replacement.

**Comment by radomird** [comment]
To turn on GitHub discussions for this repo you need admin rights to access "Settings" here is a link that explains the steps on how to enable it: https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository

I will create a PR that removes the Spectrum badge.
