### ISSUE TITLE
The build job is failing due the "typescript-examples" build

### ISSUE THREAD

**Issue by gdorsi** [nearform/graphql-hooks#734]
I have altready tried to:
- [invalidate the cache](https://github.com/nearform/graphql-hooks/actions/runs/1582359549)
- [downgrade typescript](https://github.com/nearform/graphql-hooks/actions/runs/1582423484)
- [disable eslint](https://github.com/nearform/graphql-hooks/runs/4533184131?check_suite_focus=true)

nothing worked

**Comment by simoneb** [comment]
does it fail locally as well?

**Comment by gdorsi** [comment]
Yes, when the npm install is performed with with node 16.13.1 (and npm 8.1.2)

**Comment by simoneb** [comment]
interesting, I wouldn't have really expected this to be affected by the node version!
