### ISSUE TITLE
The "typescript-examples" build breaks when the deps are installed with npm ^8.1.2 (node ^16.13.1)

### ISSUE THREAD

**Issue by gdorsi** [nearform/graphql-hooks#735]
The error is `Cannot read properties of undefined (reading 'includes')` and is generated by `mini-css-webpack-plugin`

**Comment by liana-pigeot** [comment]
I had this issue too earlier. It probably has something to do with Lerna because it works fine if I run `npm install` inside the `typescript` folder directly. It also works on CI. So it seems to be specifically the lerna bootstrap doing something wrong

**Comment by gdorsi** [comment]
To make the CI pass we have pinned the node version https://github.com/nearform/graphql-hooks/pull/736/files

**Comment by wilkmaia** [comment]
@gdorsi can you confirm whether this issue is still happening?

In the current [`master`](https://github.com/nearform/graphql-hooks/tree/4cb3dc0) I'm able to install all deps and build the project, including `typescript-example`.

```
lerna success run Ran npm script 'build' in 7 packages in 18.5s:
lerna success - create-react-app
lerna success - fastify-ssr
lerna success - subscription
lerna success - typescript-example
lerna success - babel-plugin-extract-gql
lerna success - graphql-hooks-memcache
lerna success - graphql-hooks
```

Or is this not what's this issue is about?

node version: `v16.14.2`
npm version: `8.5.0`

**Comment by simoneb** [comment]
@wilkmaia check the linked PR. if triggering a build on that branch (e.g. after updating it with master) still fails, then the problem is still there

**Comment by wilkmaia** [comment]
Not really sure what happened but it was likely something cached on my local setup (it'd be good to figure out what lol).

After cleaning things up (`npm run clean`) I've got the build errors in both `master` and the PR branch.

**Comment by simoneb** [comment]
@wilkmaia I'm aware that this repo is very brittle when it comes to dependencies, we've come across that several times. To this day updating some dependencies causes build errors which are hard to troubleshoot and whose simple solution is to just rollback the dependency version. Unfortunately it's a mix of several factors, among which the use of lerna, which has a hoisting behavior which is hard to figure out, and inconsistent versions of dependencies across packages. 

There are no plans to overhaul this repo at the current time.
