### ISSUE TITLE
Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'useGETForQueries')]

### ISSUE THREAD

**Issue by strivelen** [nearform/graphql-hooks#778]
I tried to test the page with Jest, but I had this problem.
![image](https://user-images.githubusercontent.com/79461399/151522518-55f2ad60-4403-4b49-bf20-72dabd761649.png)
![image](https://user-images.githubusercontent.com/79461399/151522673-7ce2db8f-002b-415c-b308-e62537c0b475.png)

**Comment by tiagoheliob** [comment]
@big-silly thanks for raising the issue, could you please set up an example repo?

**Comment by radomird** [comment]
@big-silly Do you still have this issue? If yes, could you provide and example on how are you trying to use the graphql-hooks ? Thanks!

**Comment by simoneb** [comment]
Closing as stale
