### ISSUE TITLE
Unchanged files with check annotations shows a warning in `useClientRequest.js` on line 65

### ISSUE THREAD

**Issue by radomird** [nearform/graphql-hooks#803]
### Package

`graphql-hooks`

### Description

When reviewing a PR in the `Files changed` tab the `Unchanged files with check annotations` will show an error in the `useClientRequest.js` file (see attached screenshot).
![Screenshot 2022-03-30 at 13 14 38](https://user-images.githubusercontent.com/90759187/160871697-f8a9dfb7-ed7e-4bc0-be83-91ebdccb724c.png)

**Comment by rp4rk** [comment]
This should be addressed here:
https://github.com/nearform/graphql-hooks/commit/ea4141752ac0742d17ea3b26ca930131a0b3b30f#diff-03ad0abc45e8ae8d04cc50bdeeda7da711fad3ea8f77fa465ab8c93190111d69R65

**Comment by SRHerzog** [comment]
Confirmed that this was resolved by the commit noted above.
