### ISSUE TITLE
Console messages are nested

### ISSUE THREAD

**Issue by Haroenv** [nearform/graphql-hooks#85]
### Environment

- `graphql-hooks` version: 3.2.1
- `react` version: 16.8.3
- Browser: Safari & Chrome

### Description

Second errors are nested within the first error on refetch.

screenshots are Safari & Chrome

<img width="646" alt="screenshot 2019-03-04 at 11 16 58" src="https://user-images.githubusercontent.com/6270048/53727206-ed988b00-3e6f-11e9-91b8-7e186d99bf99.png">
<img width="629" alt="screenshot 2019-03-04 at 11 18 22" src="https://user-images.githubusercontent.com/6270048/53727207-ed988b00-3e6f-11e9-84f5-b7655df8a764.png">

### How to reproduce

Something which fails, e.g. https://codesandbox.io/s/42k89kzpp7 (use expanded form to get the full console which has the error)

### Suggested solution (optional)

Error should be somewhere here, but maybe just nested groups aren't possible? 

https://github.com/nearform/graphql-hooks/blob/ae154d3a0b144416f2fe5d168585c22e74ad68ba/src/GraphQLClient.js#L45

**Comment by bmullan91** [comment]
We're missing a final `console.groupEnd()` 😅

**Comment by bmullan91** [comment]
@Haroenv fixed in `v3.2.2`

**Comment by Haroenv** [comment]
Works perfectly, thanks!

**Comment by bmullan91** [comment]
@all-contributors please add @Haroenv for bug
