### ISSUE TITLE
Header information missing after page refresh

### ISSUE THREAD

**Issue by altsel** [nearform/graphql-hooks#864]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 5.11.4
- `react` version: 18.1.0
- `next`version: 12.1.6
- Browser: google chrome

### Description

I don't think this is a bug. More or less a misconfiguration from my side.
When refreshing my browser tab I am not able to query protected content again.
It seems that the clientContext provider looses information about my bearer token which I stored after login.
I am using strapi and nextjs on the frontend. 

### How to reproduce

This is my graphQL Client config located under _app.js

```jsx
const client = new GraphQLClient({
  url: 'http://localhost:1337/graphql',
  cache: MemCacheFunction(),    
})

function MyApp({ 
  Component, 
  pageProps: {session, ...pageProps }, 
}) {
  const getLayout = Component.getLayout || ((page) => <RootLayout children={page} />)

  return getLayout(
    <SessionProvider session={session}>
      <ClientContext.Provider value={client}>
        <Component {...pageProps} />
      </ClientContext.Provider>
    </SessionProvider>
  )
}

export default MyApp
```

**Comment by matt-clarson** [comment]
@altsel how are you handling the login / where are you storing the bearer token?

**Comment by altsel** [comment]
this is my signIn fn provided by next-auth.

`await signIn("credentials", {redirect: false, email: email, password: password}).then((response) => {
      
      const promise = new Promise((resolve, reject) => {
        resolve(sessionInfo());
      })

      if(response.ok){

        promise.then((value) => {
          client.setHeader('Authorization', `Bearer ${value.jwt}`)          
        }).then(() => {
          router.replace('/');
        });
        
      } else {
        setHasError(true);
      }
    });`

Everything works as expected as long as the user does not refresh or close the browser tab in which the application is running. Is this normal behaviour?

**Comment by matt-clarson** [comment]
if you're using `next-auth` to manage getting a token and just passing that as a header to the `graphql-hooks` client, then it looks like what you're describing is a problem with how you're using `next-auth` which should provide some way of persisting the auth token across sessions

**Comment by simoneb** [comment]
@altsel to add to the feedback already provided by @matt-clarson, basically this library has no persistence mechanism, so you need to make sure that whenever you application is reinitialized (e.g. the page is refreshed), the auth information is retrieved again from whatever persistent mechanism you're storing it in and that the headers are set again on the GraphQLClient

**Comment by altsel** [comment]
thanks for your help @matt-clarson @simoneb 
I read the docs of next-auth and found the session callback where I could init graphql-hooks header information.
Unfortunately this takes place on the server side of nextjs, so I cant call any hook there.

Is there another way to add header information? Do you can think of any way to do this on the server side? Any tip?

Thanks for your help

**Comment by matt-clarson** [comment]
looking at [this guide in the next-auth docs](https://next-auth.js.org/tutorials/securing-pages-and-api-routes) it looks like you can use the `useSession` hook or pass `session` prop to `_app.js` to get the auth info in the client, where you can pass whatever you need to the graphql client - hope that helps

**Comment by altsel** [comment]
this is my _app.js. Session info is available but I have absolutely no idea how to set the header from here. Sorry most of this is all new to me ;)

```javascript
import { SessionProvider } from 'next-auth/react'
import { GraphQLClient, ClientContext } from 'graphql-hooks'
import MemCacheFunction from 'graphql-hooks-memcache'
import RootLayout from '../components/layout/root.layout'
import '../styles/globals.css'

const client = new GraphQLClient({
  url: 'http://localhost:1337/graphql',
  cache: MemCacheFunction(),    
})

function MyApp({ 
  Component, 
  pageProps: {session, ...pageProps }, 
}) {
  const getLayout = Component.getLayout || ((page) => <RootLayout children={page} />)

  return getLayout(
    <SessionProvider session={session}>
      <ClientContext.Provider value={client} session={session}>
        <Component {...pageProps} />
      </ClientContext.Provider>
    </SessionProvider>
  )
}

export default MyApp
```
