### ISSUE TITLE
Client side schema / local fields

### ISSUE THREAD

**Issue by Twipped** [nearform/graphql-hooks#865]
### Description

I tried to see if there is anything in the docs about this, but didn't find it. Apollo has functionality for defining local only state via [schema extensions](https://www.apollographql.com/docs/react/local-state/client-side-schema/) and [local only fields](https://www.apollographql.com/docs/react/local-state/managing-state-with-field-policies). Is this kind of functionality available in graphql-hooks?

If not, does it seem feasible to add (in general, not asking for effort commitment), or does this require a level of query management that goes above the library's goals?

**Comment by simoneb** [comment]
Thanks for bringing this up. This library's purpose is to communicate with a GraphQL backend. While it's an interesting feature, the ability to query local data is beyond the original intent of this library. Over time we have added features but this sounds like something that goes beyond what a graphql client library should do. 

You may want to check out if other JS clients have this feature: https://graphql.org/code/#javascript.

Would you like to share your use case so we can evaluate whether it's something that would be worth looking into?
