### ISSUE TITLE
Allow extending isExtractableFile passed to extract-files

### ISSUE THREAD

**Issue by d4rky-pl** [nearform/graphql-hooks#867]
### Description

Currently when calling `extractFiles`, a custom implementation `isExtractableFileEnhanced` is called. This implementation adds support for formdata-node and streams and it is currently not possible to extend or modify it.

### Suggested implementation

Allow passing function function for isExtractableFile (could be called instead or in tandem to the current one) to allow different File-like structures like React Native files. The simplest solution I could think of would be mixing `isExtractableFileEnhanced` and custom function in the constructor of `GraphQLClient`

Alternatively, introduce your custom File-like wrapping type. [This is what apollo-upload-client already does](https://www.npmjs.com/package/apollo-upload-client#type-reactnativefilesubstitute)

**Comment by d4rky-pl** [comment]
Sorry, I only now realized that all of this was implemented in `extract-files` 12 and this library depends on `extract-files` 11. As such, until the dependency is upgraded this is a non-issue as we can import this directly:

```
import ReactNativeFile from 'extract-files/public/ReactNativeFile'
```

I'm going to close the issue and leaving the above solution if someone runs into the same problem when migrating away from Apollo :)

**Comment by simoneb** [comment]
@d4rky-pl is there anything we can do to make it easier?
