### ISSUE TITLE
All the test suites are failing

### ISSUE THREAD

**Issue by radomird** [nearform/graphql-hooks#920]
### Package

`graphql-hooks`
`graphql-hooks-ssr`
`graphql-hooks-memcache`

### Description

When running `npm run test`, from the root of the project, all the unit test fail with a similar message (these are just a few examples):
```
error TS2339: Property 'toBe' does not exist on type 'Assertion'.
error TS2339: Property 'toHaveBeenCalled' does not exist on type 'Assertion'.
error TS2339: Property 'rejects' does not exist on type 'Assertion'.
```
### How to reproduce

Run `npm run test`.

### Suggested solution (optional)

Most likely the reason for the failures is a misconfiguration/or missing some config. 

Part of fixing this issue should be also to remove the `tsd` dependency and type tests (located in `/packages/graphql-hooks/test-d/` folder) as they are **most likely not needed anymore** since we are using `tsc` to check the types (check this [comment](https://github.com/nearform/graphql-hooks/pull/799#discussion_r833635348) and [PR](https://github.com/nearform/graphql-hooks/pull/799) for more information).

**Comment by simoneb** [comment]
it doesn't seem to be the case to me. if you go to the repo root you'll see that the last commit on master has a green checkmark

**Comment by radomird** [comment]
> it doesn't seem to be the case to me. if you go to the repo root you'll see that the last commit on master has a green checkmark

Yeah I saw that, but I can consistently reproduce it locally on `master` branch. I'm looking into it.

**Comment by simoneb** [comment]
if it succeeds in CI the most sensible assumption is that your local environment has problems, e.g. node version or other such things which deviate from how CI is configured

**Comment by radomird** [comment]
> if it succeeds in CI the most sensible assumption is that your local environment has problems, e.g. node version or other such things which deviate from how CI is configured

Well the thing is it fails in the CI as well (see the latest [PR build](https://github.com/nearform/graphql-hooks/actions/runs/3080743477/jobs/4978455546)). The issue is that Cypress global TypeScript type conflicts with Jest `expect` (see https://github.com/cypress-io/cypress/issues/22059).

**Comment by simoneb** [comment]
I still don't quite understand why the build is green on master though
