### ISSUE TITLE
setQueryData cannot receive variables or operationName.

### ISSUE THREAD

**Issue by Twipped** [nearform/graphql-hooks#930]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 6.0.0

### Description

The new `setQueryData` function released in 6.0.0 only accepts a query string for targeting query data. That means you cannot update query results if an operationName or any variables are provided for the query.

See line https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/src/GraphQLClient.ts#L429

### Suggested solution (optional)

Change `setQueryData` to accept an operation object as the first argument.

**Comment by lasmil** [comment]
I am checking this.

**Comment by simoneb** [comment]
@Twipped can you check if the linked pull request addresses your request?

**Comment by Twipped** [comment]
Spot on, thank you!
