### ISSUE TITLE
[Bug] Parameter Type for `onSuccess` Callback Function

### ISSUE THREAD

**Issue by daniel-nagy** [nearform/graphql-hooks#934]
The type does not match the value. I'm getting an object with a `data` entry.

https://github.com/nearform/graphql-hooks/blob/91cfe6c106df3b3b49c827b7f4f1435b46dc74a8/packages/graphql-hooks/src/types/common-types.ts#L178

**Comment by ilteoood** [comment]
@daniel-nagy 
I've fixed the type in the attached PR.
Let me know what you about it.
