### ISSUE TITLE
Event Listener Memory Leak

### ISSUE THREAD

**Issue by daniel-nagy** [nearform/graphql-hooks#936]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 6.0.1
  
- `graphql-hooks-memcache` version: 3.0.0
- `react` version: 18.1.0
- Browser: Brave

### Description

Fast refresh is causing `MaxListenersExceededWarning` from the **events** dependency.

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 DATA_INVALIDATED listeners added.
```

### How to reproduce

I'm using ViteJS `v3.1.6` and the @vitejs/plugin-react `v2.1.0`. The plugin uses React Fast Refresh. This appears to be a regression from graphql-hooks `v5.11.4`. I just save a file that uses graphql-hooks and after a few saves I start seeing these warnings.

### Suggested solution (optional)

Not sure, it seems the listeners are not removed on fast refresh.

**Comment by ilteoood** [comment]
Hi @daniel-nagy,
can you provide a reproduction example?
Even on stackblitz is fine.

**Comment by daniel-nagy** [comment]
@ilteoood I think I see the problem

https://github.com/nearform/graphql-hooks/blob/faa77690485bb3e646e45abb1f621984cbda0d36/packages/graphql-hooks/src/useClientRequest.ts#L292-L305

These even listeners will not be removed because a new anonymous function is being passed to `off`. A ref to the function passed to `on` needs to be passed to `off` for it to be removed correctly.
