### ISSUE TITLE
useManualQuery queryFn drilled to child component and invoked on mount does not toggle loading boolean

### ISSUE THREAD

**Issue by edreeseg** [nearform/graphql-hooks#949]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 5.11.4
- `Node` version: 14.20.0
- `react` version: 18.2.0
- Browser: Chrome/Firefox

### Description

If using `useManualQuery`, I've found that when the queryFn is drilled to a child component as a prop, the loading state on the query is not toggled properly, even though the data is retrieved. I believe this might be due to the following snippet running on mount:

```jsx
  // NOTE: state from useReducer is only initialState on the first render
  // in subsequent renders the operation could have changed
  // if so the state would be invalid, this effect ensures we reset it back
  const stringifiedCacheKey = JSON.stringify(cacheKey)
  React.useEffect(() => {
    if (!initialOpts.updateData) {
      // if using updateData we can assume that the consumer cares about the previous data
      dispatch({ type: actionTypes.RESET_STATE, initialState })
    }
  }, [stringifiedCacheKey]) // eslint-disable-line react-hooks/exhaustive-deps
  ```
  
 In the case of a manual query, the initial value of loading is `false`, which could be preventing the boolean from being toggled to `true`, although I'm not certain why this behavior differs depending on whether the queryFn is invoked in a child component or the component which contains the useManualQuery invocation. Potentially the state updates are being batched in a different manner or order in this case.

### How to reproduce

Attempt to invoke useManualQuery's queryFn after passing as a prop, on mount, as seen in the following code snippet:

https://codesandbox.io/s/musing-parm-vo2uz9?file=/src/Fetcher.tsx

We can see that the loading value never toggles from false to true, but the data is successfully retrieved. This seems to be the case both with and without React StrictMode.

Note that commenting the useEffect in `Child` out and uncommenting the useEffect in `Fetcher` causes the query to behave as expected regarding the loading boolean.

### Suggested solution (optional)

The state reset is skipped when an `updateData` option is passed. So passing
```ts
updateData: (_data: object, nextData: object) => nextData,
```
Seems to allow the loading boolean to toggle as expected. This doesn't seem to be intended, and is more so taking advantage of an implementation detail, and so I'm wondering if the reason for this issue can be elaborated on, and a better solution proposed.

Thanks, have a great day.

**Comment by andreaforni** [comment]
Hi,  I've published a PR that fixes this issue. I want to provide more context here about what I've found.

First of all, thank you @edreeseg for the detailed description and the example; it was very useful in debugging the problem :)

Let’s reuse the same example provided by @edreeseg;  we have two components, the `Parent` and the `Child`. 

In the parent, we use the `useManualQuery` hook, and we pass down to the `Child` the `data` and the `loading` flag. The child component is in charge of displaying the loading spinner and the data.

Now let’s focus on the `fetchData` call. We have two options here:
1. call it inside a `useEffect` in the parent component or
2. call it inside a `useEffect` in the child component.

```jsx
// ////////////////////////////////////////////////////////////////////////////////
// Scenario 1: call fetchData in Parent component
// ////////////////////////////////////////////////////////////////////////////////
const Child = ({loading, data}) => {
  return (
    <div>
      {loading && <div data-testid="loading">Loading...</div>}
      {data && <div data-testid="data">{data}</div>}
    </div>
  )
}

const Parent = ({query, options }) => {
  const [fetchData, { loading, data }] = useManualQuery(query, options)
  
  useEffect(() => { fetchData() }, [fetchData])

  return (
    <Child
      loading={loading}
      data={data}
    />
  )
}
```

```jsx
// ////////////////////////////////////////////////////////////////////////////////
// Scenario 2: call fetchData in Child component
// ////////////////////////////////////////////////////////////////////////////////
const Child = ({fetchData, loading, data}) => {
  useEffect(() => { fetchData() }, [fetchData])

  return (
    <div>
      {loading && <div data-testid="loading">Loading...</div>}
      {data && <div data-testid="data">{data}</div>}
    </div>
  )
}

const Parent = ({query, options }) => {
  const [fetchData, { loading, data }] = useManualQuery(query, options)
  
  return (
    <Child
      fetchData={fetchData}
      loading={loading}
      data={data}
    />
  )
}
```

The first scenario works correctly; the second one generates the bug described in the issue. 

The `useManualQuery`  hook calls the  `useClientRequest`  hook. The latter uses a reducer and actions to update the internal state. Let’s focus on two actions in particular:
- `RESET_STATE`
- `LOADING`

The `RESET_STATE` is fired when the cache key changes (it’s wrapped in a `useEffect` in the `useClientRequest` body) The `LOADING` action, on the contrary, is fired by the `fetchData` function returned by `useManualQuery`. 

What I’ve found is that the `LOADING` action can fire before or after `RESET_STATE`, based on where we call the `fetchData` function (in parent’s or child’s `useEffect`)

In the first scenario, the two actions are called in the following order:  `RESET_STATE` and then `LOADING`.

In the second scenario, the order is reversed: first `LOADING` and then `RESET_STATE`. Obviously, the latter reset the state and the loading flag.

To fix that, I updated the reducer function not to reset the state if we are loading data.

**Comment by simoneb** [comment]
@andreaforni thanks for the detailed explanation and for coming up with a fix. I wonder, is there a chance that this change you introduced, while addressing this scenario, introduces other edge cases which are not covered by tests? 

As a sanity check, and because I assume that this is a fairly common issue that similar libraries have to deal with, it would be good to check if the behavior or other similar libraries (e.g. react-query) is consistent with what we have here.

**Comment by edreeseg** [comment]
@andreaforni I'd like to thank you as well for the detailed response. Your explanation makes sense, and maps with what I'm seeing as well. I agree with what Simone mentioned in this, of course - if the fix has unexpected consequences that will end up causing problems, then it makes sense to find an alternative fix or workaround for this specific case.

Have a great rest of your week, thanks all!

**Comment by andreaforni** [comment]
Hi @edreeseg, I'm still working on this issue; in the meantime, we found a temporary workaround. If you use `useLayoutEffect` instead of `useEffect` in the `Child` component, you get the correct loading values:

```jsx
const Child = ({ names, queryIsLoading, getPokemonNames }: ChildProps) => {
  console.log('Loading is: ', queryIsLoading);

  useLayoutEffect(() => { // <- here!
    getPokemonNames();
  }, []);
  
  return queryIsLoading ? <h1>Loading</h1> : (
    <ul style={{ listStyleType: 'none' }}>
      {names.map((name) => <li key={name}>{name}</li>)}
    </ul>
  );
};
```
